### ISSUE TITLE
OSX Build fails.

### ISSUE THREAD

**Issue by opless** [heimdal/heimdal#1007]
**Describe the bug**
Following the steps in .github/workflows/osx.yml the build fails.

**To Reproduce**
```bash
git clone --depth 1 https://github.com/heimdal/heimdal/
cd heimdal
./autogen.sh
mkdir build
cd build
../configure --srcdir=`dirname "$PWD"` \
  --disable-heimdal-documentation \
  --disable-afs-support \
  --enable-maintainer-mode \
  --enable-developer \
  $CONFIGURE_OPTS \
  --prefix=$HOME/inst \
  CFLAGS="-Wno-error=shadow -Wno-error=bad-function-cast -Wno-error=unused-function -Wno-error=unused-result -Wno-error=deprecated-declarations" CFLAGS="-O0 -g -ggdb3"
make -j 10
```

results in the error:
heimdal/lib/roken/getaddrinfo.c:191:9: error: variable 'ret' set but not used [-Werror,-Wunused-but-set-variable]

**Expected behavior**
A complete build

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: OSX
 - Version: 12.4 (M1)

**Additional context**
With two CFLAGS stanzas the latter seems to overwrite the first. 
Also an extra warning suppression is needed to get it to compile.

My solution:
```bash
../configure --srcdir=`dirname "$PWD"` \
  --disable-heimdal-documentation \
  --disable-afs-support \
  --enable-maintainer-mode \
  --enable-developer \
  $CONFIGURE_OPTS \
  --prefix=$HOME/inst\
  CFLAGS="-Wno-error=shadow -Wno-error=bad-function-cast -Wno-error=unused-function -Wno-error=unused-result -Wno-error=deprecated-declarations -Wno-error=unused-but-set-variable -O0 -g -ggdb3"
```

(edited to include code markdown tags, further editing to correct initial compile error.)

**Comment by jaltman** [comment]
macOS clang 14.0 build completed without 

  CFLAGS="-Wno-error=shadow -Wno-error=bad-function-cast -Wno-error=unused-function -Wno-error=unused-result -Wno-error=deprecated-declarations"
