### ISSUE TITLE
client can cause kadmind to use uninitialized heap pointer

### ISSUE THREAD

**Issue by rtmrtmrtmrtm** [heimdal/heimdal#1051]
When a client of kadmind sends a kadm_modify message,
kadmind_dispatch() calls kadm5_ret_principal_ent() to parse the
message content, which calls kadm5_ret_key_data(). If
kadm5_ret_key_data() gets a parse error, it returns an error code
without fully parsing the message and perhaps without initializing
key->key_data_contents[0], which is a pointer. ret_principal_ent()
never does anything with the error code:

    if (mask & KADM5_KEY_DATA) {
        CHECK(krb5_ret_int32(sp, &tmp));
        princ->n_key_data = tmp;
        princ->key_data = malloc(princ->n_key_data * sizeof(*princ->key_data));
        if (princ->key_data == NULL && princ->n_key_data != 0)
            return ENOMEM;
        for(i = 0; i < princ->n_key_data; i++)
            ret = kadm5_ret_key_data(sp, &princ->key_data[i]);
    }

and goes on to read the rest of the message, and can return 0 (no
error). The result is that kadmind_dispatch() may end up seeing no
error, but ent.key_data[x].key_data_contents[y] contains whatever
garbage was in the allocated heap block. One place that garbage
pointer is used is when it's passed to memset() when
kadmind_dispatch() calls kadm5_free_principal_ent().

One way kadm5_ret_key_data() can return early is if krb5_ret_data()
reads a ridiculously large size from the client message.

I've attached a demo program that, on my setup, provokes this bug
when run with a debugging malloc that fills heap blocks with junk.
Here's a gdb backtrace:

#0  memset () at /usr/src/lib/libc/amd64/string/memset.S:146
#1  0x000000082281cf77 in kadm5_free_key_data (n_key_data=0x8209cdb24, 
    key_data=<optimized out>, server_handle=<optimized out>) at free.c:46
#2  kadm5_free_principal_ent (server_handle=server_handle@entry=0x82e34f000, 
    princ=princ@entry=0x8209cdab0) at free.c:68
#3  0x000000000020a36a in kadmind_dispatch (kadm_handlep=0xa5a5a5a5a5a5a5a5, 
    in=0x8209cda70, ac=0x82e33c070, fd=0, out=0x8209cdb48, readonly=0, 
    initial=<optimized out>) at server.c:416
#4  v5_loop (contextp=0x82e322000, ac=0x82e33c070, 
    kadm_handlep=0xa5a5a5a5a5a5a5a5, fd=0, readonly=0, initial=<optimized out>)
    at server.c:1034
#5  handle_v5 (contextp=0x82e322000, keytab=<optimized out>, 
    fd=<optimized out>, readonly=0) at server.c:1134
#6  kadmind_loop (contextp=0x82e322000, keytab=<optimized out>, 
    sock=<optimized out>, readonly=0) at server.c:1163
#7  0x000000000020b23e in main (argc=<optimized out>, argv=<optimized out>)
    at kadmind.c:223

Here's my krb5.conf. I've installed Heimdal in /usr/heimdal, and told it to
use /usr/var-heimdal instead of /var/heimdal.

[libdefaults]
    default_realm = EXAMPLE.ORG
[realms]
    EXAMPLE.ORG = {
        kdc = 127.0.0.1:8008
        admin_server = localhost:7490
    }
[domain_realm]
    .example.org = EXAMPLE.ORG

Here's what I do to run this demo on my FreeBSD 13.1 test machine:

setenv LD_LIBRARY_PATH /usr/heimdal/lib
setenv KRB5_CONFIG /usr/heimdal/etc/krb5.conf
rm -rf /usr/var-heimdal/* /usr/heimdal/etc/krb5.keytab
echo root/admin@EXAMPLE.ORG all > /usr/var-heimdal/kadmind.acl
echo root@EXAMPLE.ORG all >> /usr/var-heimdal/kadmind.acl
/usr/heimdal/sbin/kstash --random-key
/usr/heimdal/bin/kadmin -l
  init EXAMPLE.ORG
  ext_keytab -k /usr/heimdal/etc/krb5.keytab kadmin/admin kadmin/changepw
  add root
/usr/heimdal/libexec/kdc -c /usr/heimdal/etc/krb5.conf -P 8008 &
/usr/heimdal/libexec/kadmind -c /usr/heimdal/etc/krb5.conf -p 7490 &
/usr/heimdal/bin/kinit root
cc -L/usr/heimdal/lib hadmind7a.c -lkrb5
./a.out
ls -l kadmind.core

And here's the demo client, hadmind7a.c:

[hadmind7a.txt](https://github.com/heimdal/heimdal/files/10262741/hadmind7a.txt)

**Comment by nicowilliams** [comment]
Thanks so much for this report.  I will test this fix:

```
diff --git a/lib/kadm5/marshall.c b/lib/kadm5/marshall.c
index 9d24233ba6e..46b42f63cbb 100644
--- a/lib/kadm5/marshall.c
+++ b/lib/kadm5/marshall.c
@@ -374,7 +374,7 @@ ret_principal_ent(krb5_storage *sp,
        princ->key_data = malloc(princ->n_key_data * sizeof(*princ->key_data));
        if (princ->key_data == NULL && princ->n_key_data != 0)
            return ENOMEM;
-       for(i = 0; i < princ->n_key_data; i++)
+       for(i = 0; ret == 0 && i < princ->n_key_data; i++)
            ret = kadm5_ret_key_data(sp, &princ->key_data[i]);
     }
     if (mask & KADM5_TL_DATA) {
```

**Comment by nicowilliams** [comment]
I've got a test program for a subset of the kadmin protocol for fuzzing with AFL.  Making more of the kadmin stack fuzzable is a task for another day.
![image](https://user-images.githubusercontent.com/604851/209069617-291b0aa3-9002-4f62-9661-e5a59cdee0b9.png)

**Comment by nicowilliams** [comment]
Now fuzzing with the bug fix reverted.

**Comment by nicowilliams** [comment]
This is fixed in `master`.
