### ISSUE TITLE
client can cause incorrect call to DB_close in kadm5_s_create_principal()

### ISSUE THREAD

**Issue by rtmrtmrtmrtm** [heimdal/heimdal#1055]
kadm5_s_create_principal() says:

    if ((mask & KADM5_ATTRIBUTES) &&
        (princ->attributes & (KRB5_KDB_VIRTUAL_KEYS | KRB5_KDB_VIRTUAL)) &&
        !(princ->attributes & KRB5_KDB_MATERIALIZE)) {
        ret = KADM5_DUP; /* XXX */
        goto out;
    }

    ...;

out:
    if (!context->keep_open) {
        kadm5_ret_t ret2;
        ret2 = context->db->hdb_close(context->context, context->db);
        if (ret == 0 && ret2 != 0)
            ret = ret2;
    }
    hdb_free_entry(context->context, context->db, &ent);
    return _kadm5_error_code(ret);

By setting the right bits in mask and princ->attributes, the client
can cause the "goto out" to skip over the code that opens the
database, so that hdb_close() is called even though it was not opened.

There also might be the possibility of calling hdb_free_entry() even
though ent hasn't been fully initialized.

I've attached a fake client that, on my setup, causes kadmind to call
hdb_close() incorrectly. It sends a mask of 0x11, and a
princ->attributes of 0x600100.

#2  0x0000000800663109 in abort () from /lib/libc.so.7
#3  0x00000008009a042b in heim_abortv (fmt=<optimized out>, 
    ap=<optimized out>, ap@entry=0x7fffffffe100) at heimbase.c:525
#4  0x000000080099fd22 in heim_abort (
    fmt=0x18857 <error: Cannot access memory at address 0x18857>)
    at heimbase.c:510
#5  0x00000008002cde5b in DB_close (context=<optimized out>, db=0x6) at db.c:56
#6  0x000000080025d314 in kadm5_s_create_principal (server_handle=0x80164d270, 
    princ=0x7fffffffe470, mask=17, n_ks_tuple=<optimized out>, 
    ks_tuple=<optimized out>, password=<optimized out>) at create_s.c:358
#7  0x000000000020beb3 in kadmind_dispatch (kadm_handlep=0x80164d270, 
    in=0x7fffffffe3b0, ac=0x80162e2c0, fd=0, out=0x7fffffffe580, readonly=0, 
    initial=<optimized out>) at server.c:388
#8  v5_loop (contextp=0x801600e10, ac=0x80162e2c0, kadm_handlep=0x80164d270, 
    fd=0, readonly=0, initial=<optimized out>) at server.c:1049
#9  handle_v5 (contextp=0x801600e10, keytab=<optimized out>, 
    fd=<optimized out>, readonly=0) at server.c:1149
#10 kadmind_loop (contextp=0x801600e10, keytab=<optimized out>, 
    sock=<optimized out>, readonly=0) at server.c:1178
#11 0x000000000020c6fe in main (argc=<optimized out>, argv=<optimized out>)
    at kadmind.c:223

**Comment by rtmrtmrtmrtm** [comment]
Here's a demo client.
[hadmind3b.txt](https://github.com/heimdal/heimdal/files/10319103/hadmind3b.txt)

**Comment by lhoward** [comment]
Looks like `KADM5_DUP` should be returned immediately in both cases, but likely we should also review which error conditions cause the HDB to be closed if `context->keep_open` is false.

I'm surprised static analysis tools didn't catch this prior.

**Comment by nicowilliams** [comment]
Thanks for the report!  I've looked at all possible cases of this in `lib/kadm5` and pushed a fix.

(We should really migrate this entire codebase to D/Zig/Rust.)

**Comment by nicowilliams** [comment]
I'll write a test separately, and also let's add some fuzzing capability to kadmind.  I'm thinking of reusing the bits in `test_marshall` and have an option to `kadmind` to read an RPC to send to itself, then we can use AFL with that.
