### ISSUE TITLE
kpasswdd can read beyond the end of a client message

### ISSUE THREAD

**Issue by rtmrtmrtmrtm** [heimdal/heimdal#1058]
verify() in kpasswdd.c reads a 16-bit ap_req_len length out of the
client message, but doesn't check it against the received length:

    ap_req_len = (msg[4] << 8) | (msg[5]);
    if (ap_req_len == 0) {
        krb5_warnx (context, "Request is error packet (ap_req_len == 0)");
        return 1;
    }

    ap_req_data.data   = msg + 6;
    ap_req_data.length = ap_req_len;

    ret = krb5_rd_req (context,
                       auth_context,
                       &ap_req_data,
                       NULL,
                       keytab,
                       NULL,
                       ticket);

Later, in _asn1_decode(), lines 894 and 946 of lib/asn1/template.c:

            ret = der_match_tag_and_length(p, len, A1_TAG_CLASS(t->tt),
                                           &dertype, A1_TAG_TAG(t->tt),
                                           &datalen, &l);
           ...;
           } else if (datalen > len)
                return ASN1_OVERRUN;

The client can cause len (which is ap_req_len) to be much bigger than the actual message
length, so _asn1_decode() can proceed to read beyond the end of the
message.

I've attached a demo client that, on my setup, causes kpasswdd to
crash due to this problem.

#0  der_get_tag (
    p=p@entry=0x80000000e064 <error: Cannot access memory at address 0x80000000e064>, len=1, type=0x7fffffffdb50, type@entry=0x7fffffffda30, 
    cls=<optimized out>, tag=<optimized out>, size=<optimized out>)
    at der_get.c:683
#1  der_match_tag2 (
    p=p@entry=0x80000000e064 <error: Cannot access memory at address 0x80000000e064>, len=1, cls=ASN1_C_CONTEXT, type=0x7fffffffdb50, 
    type@entry=0x7fffffffda30, tag=3, size=<optimized out>) at der_get.c:734
#2  der_match_tag_and_length (
    p=p@entry=0x80000000e064 <error: Cannot access memory at address 0x80000000e064>, len=1, cls=ASN1_C_CONTEXT, type=type@entry=0x7fffffffdb50, tag=3, 
    length_ret=length_ret@entry=0x7fffffffdb40, size=0x7fffffffdb20)
    at der_get.c:768
#3  0x000000080059844b in _asn1_decode (t=<optimized out>, 
    flags=flags@entry=0, 
    p=0x80000000e064 <error: Cannot access memory at address 0x80000000e064>, 
    p@entry=0x7fffffffe073 "\237", len=1, data=0x7fffffffdea0, 
    size=size@entry=0x7fffffffdca8) at template.c:894
#4  0x0000000800598c86 in _asn1_decode (t=<optimized out>, 
    flags=flags@entry=0, p=0x7fffffffe073 "\237", 
    p@entry=0x7fffffffe06c "\037\020\204", len=<optimized out>, data=0x3, 
    size=size@entry=0x7fffffffddc8) at template.c:997
#5  0x0000000800598c86 in _asn1_decode (t=<optimized out>, 
    t@entry=0x8005a90d0 <asn1_AP_REQ>, flags=flags@entry=0, 
    p=0x7fffffffe06c "\037\020\204", p@entry=0x7fffffffe066 "N\204", 
    len=<optimized out>, len@entry=65535, data=0x3, data@entry=0x7fffffffde90, 
    size=size@entry=0x7fffffffdf08) at template.c:997
#6  0x000000080059c876 in _asn1_decode_top (t=0x8005a90d0 <asn1_AP_REQ>, 
    flags=1, p=0x2 <error: Cannot access memory at address 0x2>, 
    len=140737488345936, data=0x7fffffffde90, size=0x7fffffffdb40)
    at template.c:3080
#7  0x0000000800316bee in krb5_decode_ap_req (context=0x80101a000, 
    inbuf=0x7fffffffe5e0, ap_req=0x7fffffffde90) at rd_req.c:113
#8  krb5_rd_req_ctx (context=context@entry=0x80101a000, 
    auth_context=auth_context@entry=0x7fffffffe6a8, 
    inbuf=inbuf@entry=0x7fffffffe5e0, server=server@entry=0x0, 
    inctx=inctx@entry=0x80101d2c0, outctx=outctx@entry=0x7fffffffe010)
    at rd_req.c:871
#9  0x0000000800316abd in krb5_rd_req (context=0x80101a000, 
    auth_context=auth_context@entry=0x7fffffffe6a8, 
    inbuf=inbuf@entry=0x7fffffffe5e0, server=server@entry=0x0, 
    keytab=keytab@entry=0x801034000, ap_req_options=ap_req_options@entry=0x0, 
    ticket=0x7fffffffe6b0) at rd_req.c:715
#10 0x000000000020470c in verify (auth_context=0x7fffffffe6a8, 
    keytab=0x801034000, ticket=0x7fffffffe6b0, out_data=0x7fffffffe618, s=5, 
    sa=0x7fffffffe460, sa_size=16, msg=0x7fffffffe060 "", len=80, 
    client_addr=0x7fffffffe650, version=<optimized out>) at kpasswdd.c:489
#11 process (keytab=0x801034000, s=5, sa=0x7fffffffe460, sa_size=16, 
    msg=0x7fffffffe060 "", len=<optimized out>, this_addr=<optimized out>)
    at kpasswdd.c:615
#12 doit (keytab=0x801034000, port=16900200) at kpasswdd.c:764
#13 main (argc=<optimized out>, argv=<optimized out>) at kpasswdd.c:904

[hpasswdd2a.txt](https://github.com/heimdal/heimdal/files/10329353/hpasswdd2a.txt)

**Comment by nicowilliams** [comment]
Fixed with 1baec53f8de.
