### ISSUE TITLE
potential for kdc to use uninitialized pointer

### ISSUE THREAD

**Issue by rtmrtmrtmrtm** [heimdal/heimdal#1059]
I don't know if the following potential problem can really happen.

This code in tgs_build_reply() is executed when kdc processes a TGS
request:

   HDB *clientdb;
   ...;
   ret = _kdc_db_fetch_client(context, config, flags, priv->client_princ,
                              cpn, our_realm, &clientdb, &priv->client);
   if (ret)
       goto out;
   flags &= ~HDB_F_SYNTHETIC_OK;
   priv->clientdb = clientdb;

However, _kdc_db_fetch_client() can return zero without having set
clientdb, so that priv->clientdb is set to the garbage value in
clientdb.

This can happen if _kdc_db_fetch() sees a KRB5_NT_ENTERPRISE_PRINCIPAL
for which krb5_parse_name() returns
KRB5_PARSE_MALFORMED. _kdc_db_fetch_client() returns zero if it sees
this error from _kdb_db_fetch(), leaving clientdb unmodified.

Since tgs_build_reply() didn't see an error, processing would continue
with garbage in priv->clientdb; eventually _kdc_audit_request() would
try to use r->clientdb and crash.

Even though the principal involved arrives in a message from the client,
I think it's actually in the ticket, and thus probably not in the client's
control. Still, maybe tgs_build_reply() should say "HDB *clientdb = NULL;".

**Comment by nicowilliams** [comment]
I think this could happen, indeed.  Thanks for the report!
