### ISSUE TITLE
GSS_KRB5_GET_AUTHTIME_X truncates `time_t` on 64-bit platforms

### ISSUE THREAD

**Issue by lhoward** [heimdal/heimdal#1073]
`get_authtime()` in `krb5/inquire_sec_context_by_oid.c` encodes the ticket authtime as a `uint32_t` which will truncate on 64-bit platforms (or 32-bit with 64-bit `time_t`).

To be honest, it's probably just safe to cast without encoding as the mechglue and mechanism should always be running in the same platform / address space (well, at least platform). Otherwise, we need to add 64-bit encoder helpers.

**Comment by nicowilliams** [comment]
This is part of a larger problem we have with 32-bit time in Heimdal.

We really need to just change to using `unsigned uint32_t` everywhere we use 32-bit signed `time_t` or `int32_t` time values.

Switching to 64-bit time values will take significantly more effort and will involve some ABI breakage.  Obviously changing some ABI elements from 32-bit signed to 32-bit unsigned will also be an ABI break, but presumably it will be a much easier change for dependents to deal with (well, maybe, maybe they won't notice and fail to adjust).

**Comment by lhoward** [comment]
Have a look at the PR, this doesn’t affect a public ABIz

**Comment by lhoward** [comment]
It’s just about preserving the size of time_t across a mech to glue boundary.
