### ISSUE TITLE
Checks are not skipped when building package `heimdal=1.7~git20150920+dfsg-4ubuntu1.16.04.1+esm3` from source

### ISSUE THREAD

**Issue by mstetsyuk** [heimdal/heimdal#1076]
**Describe the bug**
Under the policy, building deb package from source should not run checks when provided with env var `DEB_BUILD_OPTIONS="nocheck"`:
https://www.debian.org/doc/debian-policy/ch-source.html#debian-rules-and-deb-build-options

However, this is what `override_dh_auto_test` target in `debian/rules` looks like in your case:
```
override_dh_auto_test:
        $(MAKE) check
```

So checks are still run when `nocheck` in `DEB_BUILD_OPTIONS` is provided.

**Expected behavior**
`override_dh_auto_test` target in `debian/rules` should normally look like this:
```
      override_dh_auto_test:
      ifeq (,$(filter nocheck,$(DEB_BUILD_OPTIONS)))
              ./run-upstream-testsuite
      endif
```

This way checks are not run when `DEB_BUILD_OPTIONS="nocheck"` is provided.

**Comment by abartlet** [comment]
Please file Debian issues with Debian, Heimdal upstream does not provide packaging. 

Sorry!
