### ISSUE TITLE
Certificate verification failed - certificate chain uses expired certificate

### ISSUE THREAD

**Issue by mskyttner** [heimdal/heimdal#1082]
Failed to fetch https://linuxrepo.heimdalsecurity.com/apt-repo/dists/stable/InRelease  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.

**To Reproduce**

```bash
curl https://linuxrepo.heimdalsecurity.com/pgp-key.public | sudo gpg --yes --dearmor -o /usr/share/keyrings/heimdal-keyring.gpg
```

**Expected behavior**
Command should work.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser: curl

**Additional context**
Appeared today when doing a "sudo apt update".

**Comment by jaltman** [comment]
heimdalsecurity.com is not associated with github.com/heimdal/

**Comment by jaltman** [comment]
The github verified domains are 

- h5l.org
- heimdal.software
- heimdal.team
-
