### ISSUE TITLE
hdb-mdb: sometimes fails to open database when processing concurrent requests

### ISSUE THREAD

**Issue by jirkanov** [heimdal/heimdal#1090]
**Describe the bug**
After upgrading to lmdb-0.9.27 or higher, Heimdal sometimes fails to open the LMDB database. It logs this message:
`Failed to open database: opening /var/heimdal/heimdal: Invalid argument`
The probability of this happening is higher when there are more requests at the same time.
I can see this with versions 7.7.0, 7.7.1, 7.8.0 and also with the current git head.
It does not happen with lmdb-0.9.26 or lower.

**To Reproduce**
1. configure Heimdal with `./configure --prefix=/usr/local/heimdal-git --disable-static --disable-afs-support --disable-ndbm-db --disable-otp --disable-hdb-openldap-module --without-berkeley-db --with-x=no`
2. `make && sudo make install`
3. initialize the db: `kadmin -l init TEST; kadmin -l add jirka@TEST`
4. `/usr/local/heimdal-git/libexec/kdc -c /tmp/krb5.conf`
5. run two scripts that try authentication in a loop: `./test.pl & ./test.pl &`
6. one or both scripts fail to authenticate after a short while

`/tmp/krb5.conf`: 
```[realms]
TEST = {
  kdc = localhost:88
}
[logging]
  kdc = SYSLOG:LOCAL4:NOTICE
```
`test.pl`:
```#!/usr/bin/perl
use Authen::Krb5::Simple;
my $krb = Authen::Krb5::Simple->new(
    realm => 'TEST',
);
while (1) {
    $krb->authenticate('jirka', 'heslo')
        or die "User: $user authentication failed: " . $krb->errstr . "\n";
}
```
**Expected behavior**
I expect the scripts to keep running and no logged error messages.

**Desktop:**
 - OS: Gentoo Linux

**Additional context**
After digging deeper, I can tell that the error occurs when LMDB's `mdb_txn_renew0` calls `LOCK_MUTEX` - the `pthread_mutex_lock` returns `EINVAL`. So it seems the mutex is incorrectly initialized, maybe due to some race? However, moving `HEIMDAL_MUTEX_lock` before the call to `calloc` in `my_mdb_env_create_and_open` does not help. On the other hand, when I compiled `lmdb-0.9.30` with robust mutexes disabled (`#define MDB_USE_ROBUST 0`), I could not reproduce the problem.

Another potentially related observation: the `hdb-mdb` function `my_mdb_env_create_and_open` looks for an existing env in `keep_them_open`, but while I was tracing the code, it never happend that it would find one. Which is odd, considering I ran many requests at the same time. I am probably misunderstanding the code, but I thought the env should be (re)used by all threads.

**Comment by hyc** [comment]
There's no changes to mutex handling or environment initialization between 0.9.26 and 0.9.27. Does your distro perhaps have some local/private patches to your LMDB build?

**Comment by jirkanov** [comment]
No, sorry, I should have mentioned that I compiled and used the vanilla lmdb-0.9.30, not the one from my distribution.

Now I checked a completely different machine (with an ancient Fedora version) where I compiled heimdal-7.8.0 + lmdb-0.9.29 and I see can see the occasional `Failed to open database: opening /var/heimdal-smtpd/heimdal: Invalid argument` in the logs, too.

**Comment by nicowilliams** [comment]
> Another potentially related observation: the `hdb-mdb` function `my_mdb_env_create_and_open` looks for an existing env in `keep_them_open`, but while I was tracing the code, it never happend that it would find one. Which is odd, considering I ran many requests at the same time. I am probably misunderstanding the code, but I thought the env should be (re)used by all threads.

That's for threaded applications.  All in-tree consumers of HDB are single-threaded.

That disabling robust locks made the problem go away makes it sound like a process that was using the HDB died while holding the lock.  Can you check for that?

**Comment by jirkanov** [comment]
It seems it's a bug in LMDB after all.

The reason why disabling robust locks made the problem go away is that `pthread_mutex_destroy` isn't then called on the mutex.  
The issue is that `mdb_env_setup_locks` initializes the mutex only when it gets an exclusive fcntl file lock. But there is this possible order of operations:

1. Process A opens the DB, gets an exclusive file lock, initializes the mutex, downgrades the file lock to shared and does its thing 
2. Process A closes the env: it gets an exclusive lock and destroys the mutex
3. Process B opens the DB and blocks in `mdb_env_excl_lock` trying to get the shared lock
4. Process A finishes closing the env, closes the file descriptor and loses the file lock
5. Process B gets the shared lock, does not initialize the mutex in `mdb_env_setup_locks` (because it does not have the exclusive lock)
6. Process B tries to lock the mutex, but it is not initialized, `pthread_mutex_lock` returns EINVAL

So I'm closing this issue and will open a new one in the OpenLDAP Bugzilla.

**Comment by hyc** [comment]
Thanks @jirkanov for the analysis. A bit ugly, but we can probably fix this in LMDB by doing one attempt at an exclusive lock after acquiring the shared lock.

**Comment by nicowilliams** [comment]
@hyc just don't destroy shared mutexes.

**Comment by nicowilliams** [comment]
> we can probably fix this in LMDB by doing one attempt at an exclusive lock after acquiring the shared lock.

That might kill performance under load (contention).  See https://github.com/openssl/openssl/issues/20286 for a similar situation (read rwlocks upgraded to write rwlocks).

**Comment by jirkanov** [comment]
I created a new issue here: https://bugs.openldap.org/show_bug.cgi?id=10058
