### ISSUE TITLE
kinit has annoying pause with IPv4-only client, dual-stack IPv4/IPv6 KDC

### ISSUE THREAD

**Issue by riastradh** [heimdal/heimdal#1158]
**Describe the bug**
When running kinit on an IPv4-only client, in a realm whose KDC is dual-stack, i.e., has both A and AAAA records for IPv4 and IPv6 connectivity, kinit sometimes hangs waiting for the IPv6 connection to time out before trying IPv4.

**To Reproduce**
1. Create a KDC with A and AAAA records.  (Example: realm NETBSD.ORG, KDC kerberos.netbsd.org.)
2. kinit user@REALM
3. enter a password, any password

**Expected behavior**
kinit should more or less immediately try IPv4 without waiting for IPv6 to time out, probably following the Happy Eyeballs algorithm of [RFC 8305](https://datatracker.ietf.org/doc/html/rfc8305) (formerly [RFC 6555](https://datatracker.ietf.org/doc/html/rfc6555)).

**Comment by nicowilliams** [comment]
This probably affects GSS-API as well, so it's got to get fixed, yeah.

**Comment by elric1** [comment]
A looked at something that might be similar quite some time ago and addressed it via d497d7e4a796c. Might be an interesting place to start looking?
