### ISSUE TITLE
macOS build of Heimdal uses deprecated SecKeychainFindGenericPassword API

### ISSUE THREAD

**Issue by riastradh** [heimdal/heimdal#1168]
**Describe the bug**
```
/Users/runner/work/heimdal/heimdal/kuser/kinit.c:795:10: error: 'SecKeychainFindGenericPassword' is deprecated: first deprecated in macOS 10.10 - SecKeychain is deprecated [-Werror,-Wdeprecated-declarations]
        osret = SecKeychainFindGenericPassword(NULL, strlen(realm), realm,
                ^
/Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/SecKeychain.h:628:10: note: 'SecKeychainFindGenericPassword' has been explicitly marked deprecated here
OSStatus SecKeychainFindGenericPassword(CFTypeRef __nullable keychainOrArray,  UInt32 serviceNameLength, const char * __nullable serviceName, UInt32 accountNameLength, const char * __nullable accountName, UInt32 * __nullable passwordLength, void * __nullable * __nullable passwordData, SecKeychainItemRef * __nullable CF_RETURNS_RETAINED itemRef)
         ^
1 error generated.
```

**To Reproduce**
submit any pull request to Heimdal

**Expected behavior**
macOS build passes (or, more generally, GitHub Actions succeed on pull request when the PR works)

**Additional context**
It looks like Apple wants things to use some kind of SecItem API, according to some random web searching and a cursory glance at this documentation: https://developer.apple.com/documentation/security/keychain_services/keychain_items

Here is another project that appears to have switched from SecKeychainFindGenericPassword to the SecItem API, which may be helpful for comparison, although it has a lot of extra goop in Python FFI wrappers:

https://github.com/jaraco/keyring/pull/522

**Comment by abartlet** [comment]
That Apple repo is not published by Apple, but uses scripts to import
from the tarballs Apple provide.  

So there may be a more recent update out there, but not imported.

**Comment by nicowilliams** [comment]
I took a look a few days ago at how to fix this, but I ran out of time and energy.  I'm tempted to disable deprecation warnings for now.

**Comment by abartlet** [comment]
That would be be the safe approach I think, at perhaps just on MacOS?

**Comment by nicowilliams** [comment]
Just in that file.
