### ISSUE TITLE
`libatomic` not linked for 64-bit atomics

### ISSUE THREAD

**Issue by jpalus** [heimdal/heimdal#1186]
**Describe the bug**
`heimdal` started to use 64-bit atomics which are not supported natively on all targets. I see there is a toggle `HEIM_BASE_ATOMICS_FALLBACK` which set (manually?) provides some fallbacks for atomics. However on most platforms `stdatomic.h` + linking against `libatomic` is enough and I think that would be preferred. The latter part is missing though -- currently `heimdal` does not check if linking `libatomic` is necessary

**To Reproduce**
1. Try to build `heimdal` for `i386`, `i486`, `armv6` or `mips`

**Expected behavior**
Build works fine.

**Actual behavior**
Build fails on missing symbols due to lack of `-latomic`.

**Desktop (please complete the following information):**
 - OS: Linux

**Comment by nicowilliams** [comment]
What targets don't provide atomics?  Also, yes, you can `#define` `HEIM_BASE_ATOMICS_FALLBACK` to get around this.  Ideally we should have autoconf checks for these.

**Comment by jpalus** [comment]
Don't have any comprehensive list but some notable examples of platforms lacking support for 8-byte (64-bit) atomics:
* i386/i486 used as a target in some OSes for 32-bit x86
* ARMv6 (or lower) which I think is still the primary target in main Linux distribution for Raspberry Pis
* 32-bit MIPS used on many routers

More exotic examples include 32-bit PPC and SPARC.

Created #1208 with an attempt to fix this issue.
