### ISSUE TITLE
Greedy LMDB

### ISSUE THREAD

**Issue by mingw-io** [heimdal/heimdal#1192]
**Describe the bug**
Issues when enabling/using lmdb backend. It creates excessively huge databases.

**To Reproduce**
Enable lmdb backend.
Run (unit) tests.

**Expected behavior**
Reasonable db size.
No issues with GNU dbm and/or SQLite databases.

**Screenshots**
![image](https://github.com/heimdal/heimdal/assets/70483213/29fac42b-9e5c-4dd9-9249-de9cea134ea2)

![image](https://github.com/heimdal/heimdal/assets/70483213/e381084a-882f-4866-ad7b-c7bd6de1dfc8)

![image](https://github.com/heimdal/heimdal/assets/70483213/85c55d66-3ec4-4888-8512-7377219a793c)

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
- lmdb 0.9.31
- Heimdal master branch

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

Thanks in advance.

**Comment by abartlet** [comment]
This is an LMDB feature.  It creates a sparse file by default, on systems that support such things. 

Except by limiting the DB size (which means that the DB cannot ever be larger, without offline changes) Heimdal can't fix this.

**Comment by quanah** [comment]
LMDB supports resizing on the fly (OpenLDAP and postfix both use this with LMDB databases).  Perhaps there's a special case why Heimdal can't do this? @hyc

**Comment by hyc** [comment]
You can build LMDB to grow the file incrementally on Windows. https://bugs.openldap.org/show_bug.cgi?id=8324 This has been a solved problem for 8 years already.

**Comment by mingw-io** [comment]
For the time being and until further notice LMDB has been disabled and/or removed from all the projects we ship, including OpenLDAP and this project among others.
Hopefully a reasonable minimum database size could be set by default in the code base so it doesn't interfere with the (unit) tests.
What strike us is that one test requires 8GB, another test 2GB, another test 1GB and so on and so on. We have never seen anything like this.
The CI server box isn't very useful/reliable either.

Anyway, lessons learned!
