### ISSUE TITLE
OSX 10.9 Doesn't build property (HAVE_STRLCPY & HAVE_STRLCAT not defined for libedit)

### ISSUE THREAD

**Issue by mabrowning** [heimdal/heimdal#120]
When building the 1.5 branch (didn't try master) on OSX 10.9, I had to manually edit lib/libedit/config.h to define HAVE_STRLCPY and HAVE_STRLCAT to build successfully. Not sure what component failed to find these stdlib definitions, but such a workaround did it for me, otherwise lib/libedit/strlcpy.c and lib/libedit/strlcat.c spewed forth duplicate & conflicting definition errors.

**Comment by jaltman** [comment]
Please try the 1.6 branch.

**Comment by mabrowning** [comment]
Ok, it built without error on the 1.6 branch. I need to continue to support 1.5, but if the issue is fixed with the in-development version, that seems sufficient. 

Hopefully if other people run into this issue, they can find this and fix their build for 1.5. The original error line that started me down the rabbit hole (for search engines to find):

../../../../lib/libedit/src/strlcat.c:45:1: error: expected parameter declarator
strlcat(char *dst, const char *src, size_t siz)

../../../../lib/libedit/src/strlcat.c:45:1: error: expected ')'
/usr/include/secure/_string.h:111:44: note: expanded from macro 'strlcat'
  __builtin___strlcat_chk (dest, src, len, __darwin_obsz (dest))

Thanks.
