### ISSUE TITLE
krb5.conf(5) man page doesn't describe, and verify_krb5_conf(8) doesn't verify, syntax of [kdc] ports

### ISSUE THREAD

**Issue by riastradh** [heimdal/heimdal#1223]
**Describe the bug**
The krb5.conf(5) man page doesn't describe the syntax of the [kdc] ports option.  All it says is:
```
                      ports = list of ports
                           List of ports the kdc should listen to.
```

verify_krb5_conf(8) doesn't verify syntax of [kdc] ports.  I can put any old garbage in there and verify_krb5_conf(8) will be happy with it.

By experiment, it looks like the syntax is a space-separated list of either:

- `+` (meaning default ports)
- _portnum_[`/`_protocol_]
- _servicename_[`/`_protocol_]

where _protocol_ is either `tcp` or `udp`, and if omitted leads to both.

**To Reproduce**
1. read krb5.conf(5) man page
2. flail around with krb5.conf options
3. run verify_krb5_conf(8) and get no useful feedback

**Expected behavior**
1. krb5.conf(5) describes the exact syntax of [kdc] ports.
2. verify_krb5_conf(8) reports errors for syntax that doesn't make sense.

**Comment by nicowilliams** [comment]
It seems it's

- `+` -> standard ports
- any name that is accepted by `getservbyname()`
- any number stopping at the first non-digit character (lame)
