### ISSUE TITLE
Default ticket lifetime value for kinit with password

### ISSUE THREAD

**Issue by riton** [heimdal/heimdal#123]
Hi,

It seems that there is a hard-coded default value for ticket lifetime when using `kinit $user` without any option. The default ticket lifetime requested by `kinit` seems to be _10 hours_ (https://github.com/heimdal/heimdal/blob/master/lib/krb5/init_creds_pw.c#L249).

I wasn't able to find any documentation about this default ticket lifetime value. 

This is **no bug at all** but maybe that this should appear somewhere in the man pages ?

Cheers

**Comment by jaltman** [comment]
I have been thinking about the default value recently.   I think it should be something large so that the constraint is applied by the KDC and not the kinit command.

**Comment by riton** [comment]
:+1: on this.

Actually, even if the default value is quite large, there will be edge cases where it will be lower than the value set on the KDC.
I'm not quite sure about what I'm going to say but maybe that the best solution would be to:
1. do not set a default value if the user has not used the `-l | --lifetime` option.

2. if 1 is not possible, set the default value to the maximum lifetime a ticket can have (if there is such maximum value) so that the KDC settings will always be used.

At least, if no change occurs about the default value, just a mention in the documentation or the man pages would be appreciated :-)

**Comment by nicowilliams** [comment]
On Wed, Feb 25, 2015 at 08:34:22AM -0800, Jeffrey Altman wrote:
> I have been thinking about the default value recently.   I think it
> should be something large so that the constraint is applied by the KDC
> and not the kinit command.

Yes.

**Comment by jaltman** [comment]
Set default to max lifetime for Heimdal 7 and update docs.

**Comment by nicowilliams** [comment]
I think there's no docs to update...

**Comment by nicowilliams** [comment]
Fixed with a013e93.

**Comment by kaduk** [comment]
> no docs to update

Could be taken as an indicator to write some docs.
(FWIW, I was unpleasantly surprised when OS X system kerberos changed to requesting longer-than-one-day tickets by default, but I expect that I am an outlier.)

**Comment by jaltman** [comment]
This is a change that must be documented in the release notes.   Organizations that rely upon restrictions on ticket lifetimes imposed by the clients are experiencing a false sense of security.   The lifetime restrictions imposed by the client distributions make it impossible for Kerberos realm administrators to control ticket lifetime policies by adjusting the values assigned to the kdc configuration and principal entries in the KDB.
