### ISSUE TITLE
[feature] Credential store extensions

### ISSUE THREAD

**Issue by frozencemetery** [heimdal/heimdal#126]
Heimdal does not currently have support for the [Credential Store extensions](http://k5wiki.kerberos.org/wiki/Projects/Credential_Store_extensions).  Especially missing for my purposes is `gss_acquire_cred_from()`, without which it's somewhat painful to specify, e.g., a keytab location in a config file.

Thanks!

**Comment by nicowilliams** [comment]
Yes, we should add these, at least gss_acquire_cred_from().
gss_store_cred_into() may not be very well-thought out.

Nico
--

**Comment by lhoward** [comment]
Duplicate of #451
