### ISSUE TITLE
lib/gssapi race condition

### ISSUE THREAD

**Issue by vriera** [heimdal/heimdal#135]
I have found this race condition. It fails to build because the header gkrb5_err.h is required before being generated:

Making all in gssapi
make[3]: Entering directory '/home/vriera/git-clones/buildroot-1/output/build/host-heimdal-1.6rc2/lib/gssapi'
../../lib/asn1/asn1_compile --option-file=./spnego/spnego.opt ./spnego/spnego.asn1 spnego_asn1
../../lib/asn1/asn1_compile ./mech/gssapi.asn1 gssapi_asn1
/usr/bin/make  all-am
make[4]: Entering directory '/home/vriera/git-clones/buildroot-1/output/build/host-heimdal-1.6rc2/lib/gssapi'
compile_et ./krb5/gkrb5_err.et
compile_et ./krb5/gkrb5_err.et
../../lib/sl/slc ./gss-commands.in
../../lib/sl/slc ./gss-commands.in
  CC       test_cred.o
  CC       test_kcred.o
  CC       test_context.o
In file included from test_context.c:34:0:
krb5/gsskrb5_locl.h:42:23: fatal error: gkrb5_err.h: No such file or directory
 #include <gkrb5_err.h>
                       ^
compilation terminated.

**Comment by nicowilliams** [comment]
Thanks for the report.
