### ISSUE TITLE
Periode toegangsverlening tot Heimdal instelbaar

### ISSUE THREAD

**Issue by GuidovanCapelleveen** [heimdal/heimdal#143]
Als gebruiker moet ik elke 30 minuten mijn Heimdal kluis opnieuw authenticeren om bij mijn wachtwoorden te kunnen. Graag zou ik net zoals bij de authenticering van een machine via Heimdal een tijdsbereik kunnen instellen waarin ik Heimdal kan gebruiken opdat ik minder vaak mijn wachtwoord hoef in te vullen.

**Comment by jaltman** [comment]
The length of time that a Kerberos ticket is valid is determined by 

1. the length of time requested by the "kinit" program 
2. the ticket lifetime configured for the user@REALM principal in the Kerberos database
3. the ticket lifetime configured for the krbtgt/REALM@REALM principal in the Kerberos database
4. the ticket lifetime configured for the service/hostname@REALM principal in the Kerberos database for the service the user is authenticating to.

The shortest lifetime of configured for all of the above is what will be used as the final ticket lifetime.

I hope that helps.

**Comment by tipt0e** [comment]
Thank you for that, and is correct within the code path(s).
