### ISSUE TITLE
Implement Change Passwort Prompt API

### ISSUE THREAD

**Issue by spaceone** [heimdal/heimdal#146]
Heimdal does not support the krb5_get_init_creds_opt_set_change_password_prompt API.
This prevents using defer_pwchange in pam_krb5 with Heimdal/Samba.
It's therefore not possible to prevent the prompt for new credentials on authentication if the password is expired.

This should be implemented!
Maybe there is a known workaround?

**Comment by spaceone** [comment]
Maybe this?: https://github.com/spaceone/heimdal/commit/d796bd55cc2156f74998a509afb570e880ce6d77

**Comment by abartlet** [comment]
The best way forward would be to make a pull request, including appropriate tests.  That will get much more attention than a bug report.

Thanks!

**Comment by spaceone** [comment]
Well, I am still developing and testing the patch.

**Comment by spaceone** [comment]
Opened PR #152.

**Comment by spaceone** [comment]
Ping.

**Comment by spaceone** [comment]
The patch was merged in https://github.com/heimdal/heimdal/commit/7422cd1f6b012c2edb4e04ec03c993b5c047611f
