### ISSUE TITLE
heimdal-bugs@h5l.org is broken

### ISSUE THREAD

**Issue by spaceone** [heimdal/heimdal#147]
Your mail address <heimdal-bugs@h5l.org> returns Undelivered Mail Returned to Sender.
```Recipient address rejected: User unknown in local recipient table```

The mail address is used on the website as well as in the README.

**Comment by jaltman** [comment]
The web site has been updated to recommend submitting requests via [GitHub](https://github.com/heimdal/heimdal/issues) instead of sending mail.   The mail address is dead.
