### ISSUE TITLE
heimdal doesn't install on MacOS X 10.11 (El Capitan)

### ISSUE THREAD

**Issue by slbayer** [heimdal/heimdal#156]
The error I get is "This package is incompatible with this version of OS X and may fail to install." If I select "Install Anyway", it gets to the end of the installation and appears to fail to write the files. I suspect the reason is that it's trying to install in /usr/heimdal, and the Mac's new System Integrity Protection (SIP) doesn't permit anything but installers to write to /usr. I've tried both 1.5.3 and 1.6rc2 and neither of them succeed. The error in the installer log is

Feb 17 19:59:30 mm206535-pc shove[965]: [source=dir, dst=notExist] failed _RelinkFile(/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/410B2DF2-F195-44D3-85C3-9123B4B5ECD0.activeSandbox/Root/usr/heimdal, /usr/heimdal): No such file or directory

I can unpack the contents of the package and place the executables elsewhere, but you should probably fix this.

**Comment by vdukhovni** [comment]
Heimdal is distributed in source form. Package creation is up to O/S release maintainers. It is unclear what upstream Heimdal is supposed to do here...  Closing.

[ Heimdal can be configured to install to and run from directories other than /usr at compile time... ]
