### ISSUE TITLE
Errors while building der-protos.h does not abort the build process

### ISSUE THREAD

**Issue by ribx** [heimdal/heimdal#165]
# I had some strange error messages when compiling the trunk version. After some digging, it turned out, that "der-protos.h" was not build correctly, because the perl script need Perl::JSON to work. In the Makefile the command to build them is

./lib/ans1/Makefile:
`cd $(srcdir) && perl ../../cf/make-proto.pl -q -P comment -o der-protos.h $(dist_libasn1base_la_SOURCES) || rm -f der-protos.h
`

which means, that no error is return, when the command does not succeed.

**Comment by ribx** [comment]
Maybe another solution is, to make sure, that Perl::JSON is installed in the configure script.

**Comment by nicowilliams** [comment]
`autogen.sh` checks for it.  The check should move into `configure.ac`.  Also, the invocation of `make-proto.pl` is not consistent everywhere...

**Comment by nicowilliams** [comment]
Fixed with 298ee93.
