### ISSUE TITLE
Suspicious code in lib/wind/ldap.c

### ISSUE THREAD

**Issue by pgiffuni** [heimdal/heimdal#169]
The following line has a repeated check:

[lhttps://github.com/heimdal/heimdal/blob/master/lib/wind/ldap.c#L68](url)

Perhaps something like this would be enough:

```
--- heimdal/lib/wind/ldap.c     (revision 297756)
+++ heimdal/lib/wind/ldap.c     (working copy)
@@ -64,8 +64,7 @@
 
     while (i < olen) {
        if (tmp[i] == 0x20) {
-           if (put_char(out, &o, 0x20, *out_len) ||
-               put_char(out, &o, 0x20, *out_len))
+           if (put_char(out, &o, 0x20, *out_len))
                return WIND_ERR_OVERRUN;
            while(i < olen && tmp[i] == 0x20) /* skip middle spaces */
                i++;

```

**Comment by jaltman** [comment]
The original code writes two space characters to the output stream.    Your change only writes one.    

Why do you believe that the existing code is incorrect?

**Comment by pgiffuni** [comment]
Hmm ... I see.
The semantic checker only cares about the logical operation so that 
if( A || A)
is the same as if (A)

The original code is correct, although the way it's written is somewhat confusing.
My error.
