### ISSUE TITLE
h5l.org invites bug-reports at a disfunctional address

### ISSUE THREAD

**Issue by UnitedMarsupials** [heimdal/heimdal#180]
Instead of asking for bug-reports to be e-mailed to `heimdal-bugs@h5l.org`, h5l.org should, probably, link to this issues-page at GitHub.

```
  Recipient address: heimdal-bugs@h5l.org
  Reason: Remote SMTP server has rejected address
  Diagnostic code: smtp;550 5.1.1 <heimdal-bugs@h5l.org>: Recipient address rejected: User unknown in local recipient table
  Remote system: dns;mail.h5l.org (TCP|206.46.173.23|36489|80.255.7.144|25) (mif.h5l.org ESMTP Postfix [Ubuntu])
```

**Comment by jelmer** [comment]
Thanks for the report. This was reported earlier as #147

**Comment by jaltman** [comment]
The web site has been updated to suggest submitting requests via [GitHub](https://github.com/heimdal/heimdal/issues) instead of sending mail.
