### ISSUE TITLE
compile error on archlinux

### ISSUE THREAD

**Issue by codingclubadbu** [heimdal/heimdal#182]
# i get this error on my machine while trying to build, can't find any reason why this should happen

```
/heimdal-1.5.2/base/.libs/libheimbase.so: undefined reference to `pthread_getspecific'
/heimdal-1.5.2/base/.libs/libheimbase.so: undefined reference to `pthread_key_create'
/heimdal-1.5.2/base/.libs/libheimbase.so: undefined reference to `pthread_setspecific'
collect2: error: ld returned 1 exit status
```

**Comment by nicowilliams** [comment]
@codingclubadbu What kind of system is that?  I.e., Linux (what distro?), OS X, ...  What version?

**Comment by jaltman** [comment]
@nicowilliams https://www.archlinux.org

**Comment by nicowilliams** [comment]
Oy, how did I miss that.

**Comment by vdukhovni** [comment]
What libc are you using?  Is it glibc, or some alternative?  On Linux, at present only glibc is supported.  You can explicitly add "LDFLAGS=-lpthread" to the environment of `configure` and see if that helps.
