### ISSUE TITLE
On solaris 10 x64, test_crypto example_evp_cipher fails on block ciphers larger then 31 bytes

### ISSUE THREAD

**Issue by dmulder** [heimdal/heimdal#194]
sol10build:~/heimdal/lib/hcrypto$ for a in 7 15 16 17 31 32 33 ; do ./example_evp_cipher $a ./test_crypto.in test-out-$a; cmp test-out-1 test-out-$a || { echo "cmp $a failed" ; exit 1; } ; done
test-out-1 test-out-32 differ: char 17, line 1
cmp 32 failed

It's not just at block size 32. Everything above 31 fails. I visually inspected the output, and the cipher text is different.

**Comment by nicowilliams** [comment]
Sounds like something is wrong in `lib/hcrypto/evp-pkcs11.c`.

**Comment by nicowilliams** [comment]
I'll debug this tomorrow.

**Comment by jaltman** [comment]
@lhoward could you look into this?

**Comment by nicowilliams** [comment]
Ah, that might be best, yes.

@dmulder can you furnish the cipher text?

**Comment by lhoward** [comment]
OK, I will take a look as soon as I can.

**Comment by nicowilliams** [comment]
It's probably this:

    296 static int
    297 p11_do_cipher(EVP_CIPHER_CTX *ctx,
    298               unsigned char *out,
    299               const unsigned char *in,
    300               unsigned int size)
    301 {
    ...
    316     /* We cannot use C_EncryptUpdate() as it may buffer the output. */
    317     if (ctx->encrypt) {
    318         rv = p11_module->C_EncryptInit(p11ctx->hSession, &mechanism, p11ctx->hSecret);
    319         if (rv == CKR_OK)
    320             rv = p11_module->C_Encrypt(p11ctx->hSession, (unsigned char *)in, size, out, &ulCipherTextLen);
    321     } else {
    322         rv = p11_module->C_DecryptInit(p11ctx->hSession, &mechanism, p11ctx->hSecret);
    323         if (rv == CKR_OK)
    324             rv = p11_module->C_Decrypt(p11ctx->hSession, (unsigned char *)in, size, out, &ulCipherTextLen);
    325     }

I think you must use C_EncryptUpdate()...

**Comment by nicowilliams** [comment]
Section 5.2 of `PKCS#11` basically says that the `Update` functions should not (really, must not) output more than can be computed, which means that we must do our own buffering here.

**Comment by nicowilliams** [comment]
@lhoward How can I configure the use of PKCS#11 on systems other than Solaris?  It'd be nice to build and test this on all platforms where we can get a PKCS#11 soft-token.  (It'd be nice, too, to have a builtin soft-token back-ended by hcrypto so that we could test that hcrypto (PKCS#11)->hcrypto (native or OpenSSL) produces the same behavior as hcrypto (native or OpenSSL).

**Comment by nicowilliams** [comment]
Hmmm, the hcrypto Init/Update/Final functions do buffer, and call the backend's `do_cipher()` with complete blocks, so we don't have to do any buffering, but we do have to call `C_EncryptUpdate()`.`C_DecryptUpdate()`.  The backend doesn't get called to finalize, but that's ok for the modes we're using here (CBC).

**Comment by nicowilliams** [comment]
Please test and review PR #207.

I cannot find a PKCS#11 soft token for testing this (sure, I can find various PKCS#11 drivers for hardware tokens, but I need a soft token).  In particular it would be nice to be able to always build (we do) and test (we only do on Solaris/Illumos) this EVP backend, as the CIs we use don't include Solaris/Illumos platforms.

**Comment by nicowilliams** [comment]
Fixed with 81c778e (see also e803b00 and 9c8b450).

**Comment by nicowilliams** [comment]
Thanks for the report!

**Comment by lhoward** [comment]
> On 12 Nov. 2016, at 5:14 am, Nico Williams <notifications@github.com> wrote:
> 
> @lhoward <https://github.com/lhoward> How can I configure the use of PKCS#11 on systems other than Solaris? It'd be nice to build and test this on all platforms where we can get a PKCS#11 soft-token. (It'd be nice, too, to have a builtin soft-token back-ended by hcrypto so that we could test that hcrypto (PKCS#11)->hcrypto (native or OpenSSL) produces the same behavior as hcrypto (native or OpenSSL).
> 
I used SoftHSM on OS X, and openCryptoki on Linux, whilst developing.

**Comment by lhoward** [comment]
Fixed without regression in a88d0066.
