### ISSUE TITLE
Test failures in current master (check-gssmask, check-context, check-spnego)

### ISSUE THREAD

**Issue by jelmer** [heimdal/heimdal#213]
There are at least three tests that fail for me in current master:

FAIL: check-gssmask
FAIL: check-context
FAIL: check-spnego

morgaine:~/src/heimdal% cat ./tests/gss/check-gssmask.log
Creating database
Doing database check
Starting kdc
Waiting for KDC to start, looking logfile messages.log
Have waited 2 seconds
Starting client 1
Starting client 2
Starting client 3
gssmaestro: krb5_ret_int32 *hContext
Connecting to slaves
Test acquire credentials
Self context tests
n1 connects to self using host/n1.test.h5l.se@TEST.H5L.SE
gssmask: krb5_ret_int32 op
gssmask: krb5_ret_int32 op
killing kdc and clients (1097, 1360, 1361, 1362)
FAIL check-gssmask (exit status: 1)

**Comment by jaltman** [comment]
Thanks for the report.   I broke them last night or this morning.   I will git bisect and fix.

**Comment by jaltman** [comment]
Fixed by d9f7718a42d25ade77c26dab1a613d383db3b7db

**Comment by jelmer** [comment]
Thanks!
