### ISSUE TITLE
7.0.1 reports variables as commands not found

### ISSUE THREAD

**Issue by quanah** [heimdal/heimdal#215]
Saw this while running configure:

```
checking for db_create... ./configure: line 16456: ac_cv_lib_db-5=yes: command not found
yes, in -ldb-5
checking for dbopen... no
checking for dbm_firstkey... ./configure: line 16694: ac_cv_lib_db-5=yes: command not found
```

**Comment by nicowilliams** [comment]
On Thu, Dec 01, 2016 at 04:38:44PM -0800, Quanah Gibson-Mount wrote:
> Saw this while running configure:
> 
> ```
> checking for db_create... ./configure: line 16456: ac_cv_lib_db-5=yes: command not found
> yes, in -ldb-5
> checking for dbopen... no
> checking for dbm_firstkey... ./configure: line 16694: ac_cv_lib_db-5=yes: command not found
> ```

Oooh, thanks!

**Comment by nicowilliams** [comment]
@quanah can you test this fix:

    diff --git a/cf/find-func-no-libs2.m4 b/cf/find-func-no-libs2.m4
    index 692001c..ebbbe1b 100644
    --- a/cf/find-func-no-libs2.m4
    +++ b/cf/find-func-no-libs2.m4
    @@ -53,7 +53,7 @@ case "$ac_res" in
            ;;
            *)
            eval "ac_cv_func_$1=yes"
    -       eval "ac_cv_lib_`echo "$ac_res" | sed 's/-l//'`=yes"
    +       eval "ac_cv_lib_`echo "$ac_res" | tr - _ | sed 's/-l//'`=yes"
            AC_DEFINE_UNQUOTED($ac_tr_func)
            AC_DEFINE_UNQUOTED($ac_tr_lib)
            AC_MSG_RESULT([yes, in $ac_res])

(Mind you, nothing in-tree uses these `ac_cv_lib_*` as set by `AC_FIND_FUNC_NO_LIBS2`...  We could just as well remove that line.)

**Comment by quanah** [comment]
@nicowilliams Same result

**Comment by nicowilliams** [comment]
@quanah What if you delete that modified line instead of modifying it?

**Comment by quanah** [comment]
@nicowilliams Same result

```
checking for db_create... ./configure: line 16456: ac_cv_lib_db-5=yes: command not found
yes, in -ldb-5
checking for dbopen... no
checking for dbm_firstkey... ./configure: line 16694: ac_cv_lib_db-5=yes: command not found
yes, in -ldb-5
checking lmdb.h usability... no
```

**Comment by nicowilliams** [comment]
Did you re-run `./autogen.sh` in the top of the source tree?  I should have mentioned the need to do that earlier :(

**Comment by quanah** [comment]
Ah, I did not... I will add that as a step. :)

**Comment by nicowilliams** [comment]
I'm so used to doing that...  (In fact, I've a script that runs that does all the steps a maintainer needs to do.)

**Comment by quanah** [comment]
The second patch removes the error... going to retry with the first patch as well.

Second patch:
```
checking db6/db.h usability... no
checking db6/db.h presence... no
checking for db6/db.h... no
checking db5/db.h usability... no
checking db5/db.h presence... no
checking for db5/db.h... no
checking db4/db.h usability... no
checking db4/db.h presence... no
checking for db4/db.h... no
checking db3/db.h usability... no
checking db3/db.h presence... no
checking for db3/db.h... no
checking db.h usability... yes
checking db.h presence... yes
checking for db.h... yes
checking for db_create... yes, in -ldb-5
checking for dbopen... no
checking for dbm_firstkey... yes, in -ldb-5
```

**Comment by quanah** [comment]
First patch definitely not good. ;)

```
checking for db_create... ./configure: line 15902: ac_cv_lib_cho: command not found
sed: -e expression #1, char 7: unknown option to `s'
yes, in -ldb-5
checking for dbopen... no
checking for dbm_firstkey... ./configure: line 16140: ac_cv_lib_cho: command not found
sed: -e expression #1, char 7: unknown option to `s'
yes, in -ldb-5
checking lmdb.h usability... no
```

**Comment by nicowilliams** [comment]
@quanah Huh.  That the first patch did not work is a bit shocking.  Can you try one more patch?


    diff --git a/cf/find-func-no-libs2.m4 b/cf/find-func-no-libs2.m4
    index 692001c..ebbbe1b 100644
    --- a/cf/find-func-no-libs2.m4
    +++ b/cf/find-func-no-libs2.m4
    @@ -53,7 +53,7 @@ case "$ac_res" in
            ;;
            *)
            eval "ac_cv_func_$1=yes"
    -       eval "ac_cv_lib_`echo "$ac_res" | sed 's/-l//'`=yes"
    +       eval "ac_cv_lib_`echo "$ac_res" | sed 's/-/_/g' | sed 's/-l//'`=yes"
            AC_DEFINE_UNQUOTED($ac_tr_func)
            AC_DEFINE_UNQUOTED($ac_tr_lib)
            AC_MSG_RESULT([yes, in $ac_res])

Thanks!  And thanks for testing earlier too.

**Comment by quanah** [comment]
So with that patch, I no longer see the errors around db*.h usability.

However, I am still seeing this one, but maybe it is not related to the patch:

```
checking for _FILE_OFFSET_BITS value needed for large files... no
checking for dlopen... ./configure: line 13371: ac_cv_lib_cho: command not found
sed: -e expression #1, char 7: unknown option to `s'
yes, in -ldl
checking for perl... perl
```

**Comment by quanah** [comment]
Nope, definitely related to the patch.  If I remove the patch, that error goes away.

**Comment by quanah** [comment]
Third patch actually has the same problems around the db commands as well.  I simply hadn't let it go far enough before I killed configure.  So so far, only the second patch works. ;)

**Comment by nicowilliams** [comment]
OK, I'm mystified, but at least we have a patch that works.
