### ISSUE TITLE
Regression: time_t wraparound on 32-bit platforms

### ISSUE THREAD

**Issue by s25g** [heimdal/heimdal#220]
7.0.1 kinit is broken on 32-bit x86:

$ kinit user
user@EXAMPLE.ORG's Password:
kinit: Password incorrect

but not if I explicitly specify a lifetime shorter than 22 years:
$ kinit -l 20y user
user@EXAMPLE.ORG's Password:
kinit: NOTICE: ticket lifetime is 1 day

$ kinit -l 22y user
user@EXAMPLE.ORG's Password:
kinit: Password incorrect

No, I didn't mistype the password. The KDC's logs indicate successful authentication in all cases; yet kinit is getting 0x96c73a29 from krb5_init_creds_get(). That's KRB5KRB_AP_ERR_MODIFIED. Digging further showed that in _krb5_extract_ticket() creds->times.endtime was negative and therefore rep->enc_part.endtime > creds->times.endtime .

I'm inclined to blame commit a013e93e95a826b321870a7e626e2cdc9be13984 for this.

The lazy workaround is to revert to a smaller default lifetime, say, 365*86400 seconds. Safer would be to explicitly guard against overflow when computing times.endtime and times.renew_till.

**Comment by nicowilliams** [comment]
On Sun, Dec 04, 2016 at 01:03:23AM -0800, s25g wrote:
> I'm inclined to blame commit a013e93e95a826b321870a7e626e2cdc9be13984
> for this.

I'm inclined to as well.

> The lazy workaround is to revert to a smaller default lifetime, say,
> 365*86400 seconds. Safer would be to explicitly guard against overflow
> when computing times.endtime and times.renew_till.

2^31 - 1 - time(NULL) will do it.

**Comment by nicowilliams** [comment]
@s25g can you test this patch?

    diff --git a/kcm/config.c b/kcm/config.c                                                                  [71/9994]
    index c780db2..768065f 100644
    --- a/kcm/config.c
    +++ b/kcm/config.c
    @@ -33,6 +33,7 @@
      */

     #include "kcm_locl.h"
    +#include "krb5_locl.h"
     #include <getarg.h>
     #include <parse_bytes.h>

    @@ -214,6 +215,19 @@ kcm_system_config_get_string(const char *string)
                                  "system_ccache", string, NULL);
     }

    +static const char *
    +max_life()
    +{
    +    static char s[64]; /* plenty */
    +    ssize_t bytes;
    +
    +    bytes = snprintf(s, sizeof(s), "%lus",
    +                 (unsigned long)KRB5_TKT_RENEW_LIFETIME_DEFAULT);
    +    if (bytes < 0 || bytes > sizeof(s) - 1)
    +        return "31557600s";
    +    return s;
    +}
    +
     static krb5_error_code
     ccache_init_system(void)                                                                                 [41/9994]
     {
    @@ -270,7 +284,7 @@ ccache_init_system(void)
        renew_life = kcm_system_config_get_string("renew_life");

         if (renew_life == NULL)
    -   renew_life = "2147483647s";
    +   renew_life = max_life();

         if (renew_life != NULL) {
        ccache->renew_life = parse_time(renew_life, "s");
    diff --git a/kuser/kinit.c b/kuser/kinit.c
    index 0d2c41b..c5cd6ee 100644
    --- a/kuser/kinit.c
    +++ b/kuser/kinit.c
    @@ -34,6 +34,7 @@
      */

     #include "kuser_locl.h"
    +#include "krb5_locl.h"

     #ifdef __APPLE__
     #include <Security/Security.h>
    @@ -425,6 +426,19 @@ store_ntlmkey(krb5_context context, krb5_ccache id,
     }
     #endif

    +static const char *
    +max_life()
    +{
    +    static char s[64]; /* plenty */                                                                      [11/9994]
    +    ssize_t bytes;
    +
    +    bytes = snprintf(s, sizeof(s), "%lus",
    +                 (unsigned long)KRB5_TKT_RENEW_LIFETIME_DEFAULT);
    +    if (bytes < 0 || bytes > sizeof(s) - 1)
    +        return "31557600s";
    +    return s;
    +}
    +
     static krb5_error_code
     get_new_tickets(krb5_context context,
                krb5_principal principal,
    @@ -553,7 +567,7 @@ get_new_tickets(krb5_context context,
                                                addrs_flag ? FALSE : TRUE);

         if (renew_life == NULL && renewable_flag)
    -   renewstr = "2147483647s";
    +   renewstr = max_life();
         if (renew_life)
        renewstr = renew_life;
         if (renewstr) {
    diff --git a/lib/krb5/krb5_locl.h b/lib/krb5/krb5_locl.h
    index 448938b..d3d5308 100644
    --- a/lib/krb5/krb5_locl.h
    +++ b/lib/krb5/krb5_locl.h
    @@ -322,11 +322,11 @@ typedef struct krb5_context_data {
     #endif

     #ifndef KRB5_TKT_LIFETIME_DEFAULT
    -# define KRB5_TKT_LIFETIME_DEFAULT 2147483647      /* seconds */
    +# define KRB5_TKT_LIFETIME_DEFAULT (2147483647 - time(NULL))       /* seconds */
     #endif

     #ifndef KRB5_TKT_RENEW_LIFETIME_DEFAULT
    -# define KRB5_TKT_RENEW_LIFETIME_DEFAULT 2147483647        /* seconds */
    +# define KRB5_TKT_RENEW_LIFETIME_DEFAULT (2147483647 - time(NULL)) /* seconds */
     #endif

     #ifdef PKINIT

Thanks.

**Comment by vdukhovni** [comment]
That leads to breakage in 2038 on 64-bit systems.  A fixed
default lifetime of 180 days should be more than sufficient,
and is *translation invariant*.  I expect not to find any
systems with 32-bit time_t by the middle of 2037.

**Comment by nicowilliams** [comment]
Ah, duh, of course.

**Comment by nicowilliams** [comment]
Ok, six months it is.

**Comment by nicowilliams** [comment]
diff --git a/kcm/config.c b/kcm/config.c                                                                  [15/9660]
    index c780db2..42f896f 100644
    --- a/kcm/config.c
    +++ b/kcm/config.c
    @@ -270,7 +270,7 @@ ccache_init_system(void)
        renew_life = kcm_system_config_get_string("renew_life");

         if (renew_life == NULL)
    -   renew_life = "2147483647s";
    +   renew_life = "6 months";

         if (renew_life != NULL) {
        ccache->renew_life = parse_time(renew_life, "s");
    diff --git a/kuser/kinit.c b/kuser/kinit.c
    index 0d2c41b..4e93c69 100644
    --- a/kuser/kinit.c
    +++ b/kuser/kinit.c
    @@ -553,7 +553,7 @@ get_new_tickets(krb5_context context,
                                                addrs_flag ? FALSE : TRUE);

         if (renew_life == NULL && renewable_flag)
    -   renewstr = "2147483647s";
    +   renewstr = "6 months";
         if (renew_life)
        renewstr = renew_life;
         if (renewstr) {
    diff --git a/lib/krb5/krb5_locl.h b/lib/krb5/krb5_locl.h
    index 448938b..4d524ce 100644
    --- a/lib/krb5/krb5_locl.h
    +++ b/lib/krb5/krb5_locl.h
    @@ -322,11 +322,11 @@ typedef struct krb5_context_data {
     #endif

     #ifndef KRB5_TKT_LIFETIME_DEFAULT
    -# define KRB5_TKT_LIFETIME_DEFAULT 2147483647      /* seconds */
    +# define KRB5_TKT_LIFETIME_DEFAULT        15778800  /* seconds */
     #endif

     #ifndef KRB5_TKT_RENEW_LIFETIME_DEFAULT
    -# define KRB5_TKT_RENEW_LIFETIME_DEFAULT 2147483647        /* seconds */
    +# define KRB5_TKT_RENEW_LIFETIME_DEFAULT  15778800  /* seconds */
     #endif

     #ifdef PKINIT

**Comment by s25g** [comment]
Latest patch (6-month fixed default lifetime) successfully tested (Linux i686 and x86_64). I still miss an explicit check against overflow, but since I know no easy, portable way to get the maximum value of type time_t this seems good enough for now.

**Comment by nicowilliams** [comment]
Overflow would happen around 2038...  We could revisit my first patch, do something like:

    ((time_t)((((intmax_t)(uintmaxt_t)(time_t)4294967295) > 0) ?
        (4294967295 - time(NULL)) : (2147483647 - time(NULL))

I.e., if `time_t` is unsigned 32-bit or 64-bit (signed or unsigned) then `4294967295 - time(NULL)` else `2147483647 - time(NULL)`.

Systems where `time_t` is signed 32-bit will have a 2038 year problem no matter what, while other 32-bit all others will then have a 2106 year problem.  Another possibility is to compute the two magic constants by doing `1 << (CHAR_BIT * sizeof(time_t) - 2` and `1 <<(CHAR_BIT * sizeof(time_t) - 1` so that where `time_t` is 64-bit then we just don't have a problem at all.

Here's a first approximation:

    /* Not quite maximum time, because this macro assumes signed time_t */
    #define HEIM_TIME_MAX ((((time_t)1 << (CHAR_BIT * sizeof(time_t) - 2)) - 1) * 2 + 1)
    
    /* Forever == seconds left till 2038 or 2106 */
    #define HEIM_FOREVER \
        ((time_t)((((intmax_t)(uintmaxt_t)(time_t)4294967295) > 0) ? \
            (HEIM_TIME_MAX - time(NULL) - 86400) : (4294967295 - time(NULL) - 86400)

(Minus 86400 because `HEIM_FOREVER` would be relative time that might be added to `time(NULL)` some time after computing `HEIM_FOREVER`.)

**Comment by kaduk** [comment]
```
/* Not quite maximum time, because this macro assumes signed time_t */
#define HEIM_TIME_MAX ((((time_t)1 << (CHAR_BIT * sizeof(time_t) - 2)) - 1) * 2 + 1)
```

Is the avoidance of shifting into the sign bit here intentional or accidental? ;)

**Comment by nicowilliams** [comment]
On Mon, Dec 05, 2016 at 02:06:36PM -0800, kaduk wrote:
> ```
> /* Not quite maximum time, because this macro assumes signed time_t */
> #define HEIM_TIME_MAX ((((time_t)1 << (CHAR_BIT * sizeof(time_t) - 2)) - 1) * 2 + 1)
> ```
> 
> Is the avoidance of shifting into the sign bit here intentional or accidental? ;)

Intentional :)

We'll not push such a patch anyways.  We'll just use 6 months as the
forever value.
