### ISSUE TITLE
7.0.1: symbol removed from libkrb5

### ISSUE THREAD

**Issue by s25g** [heimdal/heimdal#221]
Commit 7b720cf61ca9ad3763cf9d7ca3d139cfeb4ea9ef renamed the external symbol _krb5_AES_string_to_default_iterator to _krb5_AES_SHA1_string_to_default_iterator (and introduced a new _krb5_AES_SHA2_string_to_default_iterator). However, the shared library version number has not been updated.

Wouldn't it be appropriate to either increment the shared library version number (a new release is a good time for this) or keep the old symbol (presumably as an alias for the new name)?

**Comment by nicowilliams** [comment]
> Commit 7b720cf61ca9ad3763cf9d7ca3d139cfeb4ea9ef renamed the external symbol _krb5_AES_string_to_default_iterator to _krb5_AES_SHA1_string_to_default_iterator (and introduced a new _krb5_AES_SHA2_string_to_default_iterator). However, the shared library version number has not been updated.
> 
> Wouldn't it be appropriate to either increment the shared library version number (a new release is a good time for this) or keep the old symbol (presumably as an alias for the new name)?

_krb5_* are private.  They may be exported for in-tree dependents, but are not meant to be consumed by external dependents.  It would not be appropriate to change library version numbers for this sort of change.
