### ISSUE TITLE
rk_dns_srv_order exception

### ISSUE THREAD

**Issue by jaltman** [heimdal/heimdal#225]
The following SRV records will reliably cause rk_dns_srv_order() to advance 'tt' so that it points beyond the memory allocated to 'srvs'.

`_kerberos._udp.example.com        SRV service location:
          priority       = 10
          weight         = 0
          port           = 88
          svr hostname   = kerberos-1.example.com
_kerberos._udp.example.com        SRV service location:
          priority       = 10
          weight         = 0
          port           = 88
          svr hostname   = kerberos-2.example.com`

The existing code appears to work if the memory beyond the 'srvs' allocation is padded with NULLs.  However, on systems (such as Windows) where heap memory beyond the allocation is padded with 0xabababababababab this code blows up.

**Comment by nicowilliams** [comment]
> The following SRV records will reliably cause rk_dns_srv_order() to advance 'tt' so that it points beyond the memory allocated to 'srvs'.
> 
> `_kerberos._udp.example.com        SRV service location:
>           priority       = 10
>           weight         = 0
>           port           = 88
>           svr hostname   = kerberos-1.example.com
> _kerberos._udp.example.com        SRV service location:
>           priority       = 10
>           weight         = 0
>           port           = 88
>           svr hostname   = kerberos-2.example.com`
> 
> The existing code appears to work if the memory beyond the 'srvs' allocation is padded with NULLs.  However, on systems (such as Windows) where heap memory beyond the allocation is padded with 0xabababababababab this code blows up.

Thanks.

This is due to the reduction of `sum` as we pick RRs not being correct, but regardless the better thing to do is to ensure that `tt` never ends up pointing past `srvs` or that if it does then it doesn't get dereferenced.

**Comment by vdukhovni** [comment]
Fixed in 

https://github.com/heimdal/heimdal/commit/32f8564296cebb64cc978dcd6eded06e415404f3
https://github.com/heimdal/heimdal/commit/a1c505309c27593732fa6979b3d78f6f477de8e5

Thanks for the report, much appreciated.
