### ISSUE TITLE
RC2 contains oddly named manpage files 

### ISSUE THREAD

**Issue by jelmer** [heimdal/heimdal#227]
RC2 installs a number of oddly named manual pages..:

usr/share/man/man3/_home_.3.gz
usr/share/man/man3/_home_nico_.3.gz
usr/share/man/man3/_home_nico_ws_.3.gz
usr/share/man/man3/_home_nico_ws_h2_.3.gz
usr/share/man/man3/_home_nico_ws_h2_lib_.3.gz
usr/share/man/man3/_home_nico_ws_h2_lib_gssapi_.3.gz
usr/share/man/man3/_home_nico_ws_h2_lib_gssapi_gssapi_.3.gz
usr/share/man/man3/_home_nico_ws_h2_lib_gssapi_krb5_.3.gz
usr/share/man/man3/_home_nico_ws_h2_lib_gssapi_mech_.3.gz
usr/share/man/man3/_home_nico_ws_h2_lib_gssapi_netlogon_.3.gz
usr/share/man/man3/_home_nico_ws_h2_lib_gssapi_ntlm_.3.gz
usr/share/man/man3/_home_nico_ws_h2_lib_gssapi_spnego_.3.gz
usr/share/man/man3/_home_nico_ws_h2_lib_hcrypto_.3.gz
usr/share/man/man3/_home_nico_ws_h2_lib_hcrypto_libtommath_.3.gz
usr/share/man/man3/_home_nico_ws_h2_lib_hcrypto_libtommath_demo_.3.gz
usr/share/man/man3/_home_nico_ws_h2_lib_hcrypto_libtommath_etc_.3.gz
usr/share/man/man3/_home_nico_ws_h2_lib_hcrypto_libtommath_mtest_.3.gz
usr/share/man/man3/_home_nico_ws_h2_lib_hdb_.3.gz
usr/share/man/man3/_home_nico_ws_h2_lib_hx509_.3.gz
usr/share/man/man3/_home_nico_ws_h2_lib_hx509_ref_.3.gz
usr/share/man/man3/_home_nico_ws_h2_lib_krb5_.3.gz
usr/share/man/man3/_home_nico_ws_h2_lib_ntlm_.3.gz
usr/share/man/man3/_home_nico_ws_h2_lib_wind_.3.gz

**Comment by vdukhovni** [comment]
Thanks.  We'll review the dist tarball with more care for the final release next week.  These are not in git, so just ignore these for now.

**Comment by nicowilliams** [comment]
On Wed, Dec 14, 2016 at 04:41:38PM -0800, Jelmer Vernooij wrote:
> RC2 installs a number of oddly named manual pages..:
> 
> usr/share/man/man3/_home_.3.gz

Huh, so the dist tarball is broken.  I'll have to figure out how that happened and fix it.

Nico
--

**Comment by nicowilliams** [comment]
I've... no idea how to fix this.

**Comment by nicowilliams** [comment]
I've pushed fixes onto `master`.  @vdukhovni will review and cherry-pick onto the branch.  Should we do an `rc3` or just regenerate the rc2 tarball?  After all, only build code and doxygen comments changed...

**Comment by nicowilliams** [comment]
(I admit my fix for the bogus manpages is... a bit brute-force-ish.  A more correct fix will require more time, though someone with more Doxygen experience might spot the problem immediately.

**Comment by kaduk** [comment]
Please do not get in the habit of regenerating tarballs once they are published. It has a nasty tendency to cause headaches for some people.

**Comment by nicowilliams** [comment]
Fixed in rc3.
