### ISSUE TITLE
openbsd build: undefined reference to `pidfile'

### ISSUE THREAD

**Issue by ajacoutot** [heimdal/heimdal#230]
Hi.

Trying to build 7.0.3 on OpenBSD and64 current, I am running into the following error:

`/usr/bin/libtool  --tag=CC    --mode=link cc  -DTEST_SNPRINTF  -DINET6 -O2 -pipe -pthread  -L/usr/local/lib -o snprintf-test snprintf_test-snprintf-test.o libtest.la libroken.la -pthread 
libtool: link: cc -o .libs/snprintf-test -pthread -DTEST_SNPRINTF -DINET6 -O2 -pipe snprintf_test-snprintf-test.o /hack/objdirs/pobj/heimdal-7.0.3/heimdal-7.0.3/lib/roken/.libs/libtest.a -L.libs -lroken -Wl,-rpath,/usr/local/heimdal/lib
.libs/libroken.so.2.1: undefined reference to `pidfile'
collect2: ld returned 1 exit status
Error while executing cc -o .libs/snprintf-test -pthread -DTEST_SNPRINTF -DINET6 -O2 -pipe snprintf_test-snprintf-test.o /hack/objdirs/pobj/heimdal-7.0.3/heimdal-7.0.3/lib/roken/.libs/libtest.a -L.libs -lroken -Wl,-rpath,/usr/local/heimdal/lib`

Might be due to https://github.com/heimdal/heimdal/commit/12eb54d03f923b239d63dea49c13e6242e7fc8d0#diff-37e324178d57219edcad0574acfe37af

**Comment by nicowilliams** [comment]
> Trying to build 7.0.3 on OpenBSD and64 current, I am running into the following error:
> 
> .libs/libroken.so.2.1: undefined reference to `pidfile'
> collect2: ld returned 1 exit status
> 
> Might be due to https://github.com/heimdal/heimdal/commit/12eb54d03f923b239d63dea49c13e6242e7fc8d0#diff-37e324178d57219edcad0574acfe37af

Yes, but... why did autoconf think OpenBSD has pidfile()?

We do have a test for pidfile().  Can you tell us if OpenBSD has a manpage for pidfile(), and if so, what headers to include for it and what library it's in?

**Comment by nicowilliams** [comment]
Here's a link to a possibly-current `pidfule()` manpage on OpenBSD: http://man.openbsd.org/OpenBSD-current/man3/pidfile.3

Implied is that `pidfile()` is in libc...

Do you have a `config.log` about `pidfile()` that you could share?

**Comment by nicowilliams** [comment]
Looks like it's in libutil: https://github.com/openbsd/src/blob/5271000b44abe23907b73bbb3aa38ddf4a0bce08/lib/libutil/pidfile.c

We do look for it in libutil.  Very curious.

**Comment by vdukhovni** [comment]
> /usr/bin/libtool --tag=CC --mode=link cc -DTEST_SNPRINTF -DINET6 -O2 -pipe -pthread -L/usr/local/lib -o snprintf-test snprintf_test-snprintf-test.o libtest.la libroken.la -pthread

There's no libutil in the above. Are we missing anything in the Makefile?

**Comment by nicowilliams** [comment]
Oh, yes, that must be it.

**Comment by nicowilliams** [comment]
@ajacoutot Can you try this patch:

    diff --git a/lib/roken/Makefile.am b/lib/roken/Makefile.am
    index a8246b2..1a15939 100644
    --- a/lib/roken/Makefile.am
    +++ b/lib/roken/Makefile.am
    @@ -140,7 +140,7 @@ EXTRA_libroken_la_SOURCES =     \
        search.hin              \
        vis.hin

    -libroken_la_LIBADD = @LTLIBOBJS@ $(LIB_crypt)
    +libroken_la_LIBADD = @LTLIBOBJS@ $(LIB_crypt) $(LIB_pidfile)

     $(LTLIBOBJS) $(libroken_la_OBJECTS): roken.h $(XHEADERS)

?

Thanks.

**Comment by nicowilliams** [comment]
(You'll have to re-run ./autogen.sh before running ./configure though.)

**Comment by nicowilliams** [comment]
@vdukhovni I've pushed that to both, master and the release branch.

**Comment by nicowilliams** [comment]
FYI, I'll assume this fixes it if we don't hear by before long.

**Comment by nicowilliams** [comment]
Excellent.  Thanks!  Fixed with 63f2242.
