### ISSUE TITLE
German translation of kuser and krb5

### ISSUE THREAD

**Issue by ChrisLeick** [heimdal/heimdal#233]
Hi,

you can find attached the German translation of heimdal_kuser and heimdal_krb5. While translating, I've found some typos in the english original file. I've marked them with »FIXME« in the translation files.

Kind regards,
Chris
(c.leick@vollbio.de)

[de.tar.gz](https://github.com/heimdal/heimdal/files/670948/de.tar.gz)

**Comment by jaltman** [comment]
@ChrisLeick,

Thank you for this.  If possible, we would prefer a submission via a GitHub Pull Request instead of a tar file.
Is that something you can do.

Happy Holidays.

**Comment by ChrisLeick** [comment]
Hi Jeffrey,

Jeffrey Altman:

>  If possible, we would prefer a submission via a GitHub
> Pull Request instead of a tar file. Is that something you can do.

Normaly yes, but in this case something went wrong:

chris@laptop:~$ git clone git://svn.h5l.org/heimdal.git
Klone nach 'heimdal'...
fatal: unable to connect to svn.h5l.org:
svn.h5l.org: Der Name oder der Dienst ist nicht bekannt

This server isn't reachable by http, https and ping.


Kind regards and merry christmas,
Chris

**Comment by vdukhovni** [comment]
Wrong repo URL:

For access via your github SSH key:
```
$ git clone git@github.com:heimdal/heimdal.git
```
For anon HTTPS access:
```
$ git clone https://github.com/heimdal/heimdal.git
```

**Comment by ChrisLeick** [comment]
Hi Viktor,

Viktor Dukhovni:

> Wrong repo URL:

Please correct your website.


> For access via your github SSH key:
> ```
> $ git clone git@github.com:heimdal/heimdal.git

Ok. This has worked. But I'vo no write permissions to your repo:

chris@laptop:~/git/heimdal$ git commit -a
[master c69c30d] German tranlation of krb5 and kuser
 2 files changed, 2044 insertions(+)
 create mode 100644 po/heimdal_krb5/de.po
 create mode 100644 po/heimdal_kuser/de.po
chris@laptop:~/git/heimdal$ git push git@github.com:heimdal/heimdal.git
Enter passphrase for key '/home/lkc/.ssh/github': 
ERROR: Permission to heimdal/heimdal.git denied to ChrisLeick.

Kind regards,
Chris

**Comment by jaltman** [comment]
@ChrisLeick 

> But I'vo no write permissions to your repo

That is correct.  When I requested that you submit a GitHub Pull Request I hoped you would know that that meant.   Please see the GitHub documentation https://help.github.com/categories/collaborating-with-issues-and-pull-requests/ for assistance on creating a personal GitHub fork of the heimdal/heimdal repository, submitting your change to your personal fork, and then requesting that heimdal pull the change from your repo.

Thank you.

**Comment by ChrisLeick** [comment]
Hi Jeffrey,

> Please see the GitHub documentation
> https://help.github.com/categories/collaborating-with-issues-and-pull-reque
> sts/ for assistance on creating a personal GitHub fork of the
> heimdal/heimdal repository, submitting your change to your personal fork,
> and then requesting that heimdal pull the change from your repo.

Ok, I've created my personal fork:

git remote remove git@github.com:heimdal/ChrisLeick/German_Translation.git

git remote -v
origin  git@github.com:heimdal/heimdal.git (fetch)
origin  git@github.com:heimdal/heimdal.git (push)
upstream        git@github.com:heimdal/ChrisLeick/German_Translation.git 
(fetch)
upstream        git@github.com:heimdal/ChrisLeick/German_Translation.git 
(push)

Then I've created a local branch of master and committed my work in this 
branch.
git checkout -b german_translation
git commit -a
[german_translation d4414d3] German translation
 4 files changed, 2361 insertions(+)

But anything is wrong. When I push this branch to the fork it fails with:

git push upstream german_translation
fatal: remote error: 
  heimdal/ChrisLeick/German_Translation is not a valid repository name

Kind regards,
Chris

**Comment by vdukhovni** [comment]
You don't seem to have any Github repositories yet.  Perhaps your attempt to fork the Heimdal repository on Github was not successful:

https://github.com/ChrisLeick?tab=repositories

**Comment by ChrisLeick** [comment]
Hi Viktor,

that was the issue. Now, the new repository is created. Thanks!

Chris

**Comment by ChrisLeick** [comment]
While creating a new pull request, the button »new pull request« stays gray an in the window below is the message

_There isn’t anything to compare.
We couldn’t figure out how to compare these references, do they point to valid commits?_

(base is **master** and compare is **ChrisLeick/heimdal-1**)

**Comment by vdukhovni** [comment]
I think this was merged.  Can we close the issue?

**Comment by ChrisLeick** [comment]
Hi Viktor,

Yes, you can. ;-)

Kind regards,
Chris


Viktor Dukhovni:
>
> I think this was merged. Can we close the issue?
>
