### ISSUE TITLE
Homepage is out of date (doesn't mention new release)

### ISSUE THREAD

**Issue by jelmer** [heimdal/heimdal#234]
The Heimdal homepage still lists the latest release as 1.5. Is here any chance it could be updated?

**Comment by jaltman** [comment]
@quanah post-Xmas, could you submit a pull up?
Thanks.

**Comment by jelmer** [comment]
Thanks for updating the links on the homepage, @lha ; the documentation on the left hand side still refers to 1.5.

https://www.h5l.org/help.html links to the buildbot, but it is no longer running. Is travis the replacement for the buildbot or are there plans to revive the buildbot?

**Comment by jaltman** [comment]
@jelmer feel free to submit pull requests to https://github.com/heimdal/h5lweb

**Comment by jelmer** [comment]
On Sun, Jan 08, 2017 at 09:30:53PM -0800, Jeffrey Altman wrote:
> @jelmer feel free to submit pull requests to https://github.com/heimdal/h5lweb
I've submitted a pull request for buildbot
(https://github.com/heimdal/h5lweb/pull/7), but have no idea where a
current built copy of the documentation lives.

**Comment by jaltman** [comment]
@lha the web server is once again not seeing updates to the h5lweb repository.

**Comment by quanah** [comment]
This is all fixed now, closing
