### ISSUE TITLE
Issue building on CYGWIN - Need change to readline.h

### ISSUE THREAD

**Issue by vseven** [heimdal/heimdal#236]
Need a slight change to heimdal-7.1.0\lib\libedit\src\readline\readline.h

Current Line 77:
`#if !defined(__sun) && !defined(__hpux) && !defined(_AIX)`

Suggested Line 77:
`#if !defined(__sun) && !defined(__hpux) && !defined(_AIX) && !defined(_CYGWIN_)`

**Comment by vdukhovni** [comment]
Thanks, fixed in 3e509d780626c0bbafd9d43cdefab21325b85ae7

**Comment by jaltman** [comment]
@vseven Have you tried building on Cygwin with the Cygwin libreadline as is done for most Linux distributions?

**Comment by vseven** [comment]
No, just doing a standard  ./configure, make, make install.  The above seemed to be the only thing it choked on and seemed like it would be a easy fix that shouldn't affect anything else.  To be quite honest I'm hacking away trying to get Samba 4.5.3 compiled under Windows and heimdal isa pre-req that I'm getting stuck on.  If I knew more then it might not have been a issue at all but again the fix seems logical.

**Comment by jaltman** [comment]
I suspect the Cygwin libreadline is built with private patches to support the Windows console environment within which Cygwin executes.   Those private patches will not be present in the Heimdal clone.
