### ISSUE TITLE
encodes host architecture in krb5-config

### ISSUE THREAD

**Issue by jelmer** [heimdal/heimdal#237]
krb5-config currently encodes the host architecture in krb5-config, to determine what flags to pass to the linker.

This can make the build unreproducible. See also https://tests.reproducible-builds.org/debian/rb-pkg/unstable/i386/diffoscope-results/heimdal.html

I'm not sure what the best (portable) alternative is. Checking 'uname -o' ?

**Comment by jaltman** [comment]
@jelmer The link you provided is returning a 404 error.  

What aspect of the build is failing to reproduce?

**Comment by jelmer** [comment]
On Sun, Jan 08, 2017 at 09:28:56PM -0800, Jeffrey Altman wrote:
> @jelmer The link you provided is returning a 404 error.  
> 
> What aspect of the build is failing to reproduce?  
Sorry, the new build in Debian has a patch for this issue so I can't point you
at the new URL and the old build URL
must have expired.

Basically, the problem is that @CANONICAL_HOST@ can expand to different strings
(linux-gnu-amd64 vs linux-gnu-x86_64) on the same Debian hardware family.

This is a minor issue and we carry a Debian-specific patch for it, but it might
be relevant for other distributions that care about reproducibility (e.g. Fedora,
https://fedoraproject.org/wiki/Reproducible_Builds).

(e.g.
https://tests.reproducible-builds.org/debian/rb-pkg/unstable/amd64/heimdal.html
shows that Heimdal is now reproducible on Debian)

Jelmer

**Comment by jaltman** [comment]
What I am failing to understand is why when the value of @CANONICAL_HOST@ is different that the assumption is that the compiled output should be the same?   amd64 and x86_64 are not the same architecture.  They make different assumptions about the available processor instructions.   While hcrypto is not presently optimizing for the differences, it is certainly something we have discussed.

**Comment by jelmer** [comment]
On Mon, Jan 09, 2017 at 05:44:47AM -0800, Jeffrey Altman wrote:
> What I am failing to understand is why when the value of @CANONICAL_HOST@ is different that the assumption is that the compiled output should be the same?   amd64 and x86_64 are not the same architecture.  They make different assumptions about the available processor instructions.   While hcrypto is not presently optimizing for the differences, it is certainly something we have discussed. 
This particular bit of code doesn't care about the architecture, just the
linker flags.

On Debian, we use the same packages for amd64 and x86_64 so expect generated
binary packages to be the same regardless of on which of the two they were
compiled.

**Comment by prmarino1** [comment]
traditionally Debian calls it amd64, Red Hat calls it x86_64 and GCC calls it X86-64 they are all the same in the eyes of GCC. The name difference has more to do with packaging tools and the assumed location of C libraries than any thing else.
This seems to be an issue with Debian's dpkg tools and inconsistencies in how the releases state their architecture in uname.

**Comment by jelmer** [comment]
The problem is that @CANONICAL_HOST@ includes the CPU type (e.g. "armv5l", "armv6l", "armv7l"), and Debian (but I'm sure also e.g. Fedora) has broader architectures that it builds for (e.g. "armhf"). This means that there is a single (meaningless) difference in the generated package depending on what exact processor the package was built on.  

GCC output and assumed locations are not an issue. See the comments above.

The krb5-config script doesn't actually care about the architecture or CPU type. It just wants to know the host OS so it can pass the right rpath flags to the linker.

**Comment by jaltman** [comment]
@jelmer Does https://github.com/heimdal/heimdal/pull/252/ address this issue?

**Comment by jelmer** [comment]
AFAICT it doesn't resolve this issue; after that change, tools/krb5-config can still be different depending on what kind of CPU subtype it was generated on.

(Please note that this is not a blocker for Debian, we have a workaround in place. I would mark it as low priority if this bug tracker had a field for that).

**Comment by elric1** [comment]
Can you describe how it'll be different? We think that we've eliminated @CANONICAL_HOST@ from krb5-config entirely. Maybe we missed something, but please have a look at the installed artefacts to validate it.

**Comment by jaltman** [comment]
@elric1 After building master with this change applied `strings krb5-config | grep linux`  will include from the expanded shell script `case "x86_64-unknown-linux-gnu" in` or another cpu type depending on the system on which the build occurs.

**Comment by jaltman** [comment]
@jelmer @elric1 I forgot to `./autogen.sh; ./configure <options>` before rebuilding.  After the rebuild there is no trace of the `case "x86_64-unknown-linux-gnu" in` string in the krb5-config binary.

**Comment by jelmer** [comment]
On Mon, Mar 13, 2017 at 07:55:12AM -0700, Roland C. Dowdeswell wrote:
> Can you describe how it'll be different? We think that we've eliminated @CANONICAL_HOST@ from krb5-config entirely. Maybe we missed something, but please have a look at the installed artefacts to validate it.
The contents of krb5-config still differ depending on the CPU subtype AFAICT.

The use of the string @CANONICAL_HOST@ itself was never the problem, but what it
expanded to - and it still expands to different values on different CPU
subtypes.

**Comment by jelmer** [comment]
On Mon, Mar 13, 2017 at 08:56:23AM -0700, Jeffrey Altman wrote:
> @jelmer @elric1 I forgot to `./autogen.sh; ./configure <options>` before rebuilding.  After the rebuild there is no trace of the `case "x86_64-unknown-linux-gnu" in` string in the krb5-config binary.
I'll try again as well just to be sure. Currently traveling, so this might take a couple of days.

**Comment by jelmer** [comment]
On Mon, Mar 13, 2017 at 08:56:23AM -0700, Jeffrey Altman wrote:
> @jelmer @elric1 I forgot to `./autogen.sh; ./configure <options>` before rebuilding.  After the rebuild there is no trace of the `case "x86_64-unknown-linux-gnu" in` string in the krb5-config binary.

Yes, this does fix it:

% cat tools/krb5-config | grep x86

Thanks!
