### ISSUE TITLE
If mdb_stat is not present, one test fails

### ISSUE THREAD

**Issue by quanah** [heimdal/heimdal#251]
checking that principals in DB == entries in LMDB
./check-iprop: line 388: mdb_stat: command not found
./check-iprop: line 389: [: : integer expression expected
FAIL: check-iprop

**Comment by quanah** [comment]
Due to:
```
if [ "$db_type" = lmdb ]; then
    # Sanity check that we have the same number of principals at the HDB
    # and LMDB levels.
    #
    echo "checking that principals in DB == entries in LMDB"
    princs=`${kadmin} -l list '*' | wc -l`
    entries=`mdb_stat -n current-db.mdb | grep 'Entries:' | awk '{print $2}'`
    [ "`expr 1 + "$princs"`" -eq "$entries" ] || exit 1
fi
```

there is no check done to confirm mdb_stat is actually an available command.

**Comment by vdukhovni** [comment]
Perhaps the sanest thing is to make mdb_stat a build-dependency with configure not enabling lmdb in its absence.

**Comment by quanah** [comment]
I think that's not a good idea.  That's like saying you wouldn't allow software to link with the libssl development libraries from OpenSSL because the "openssl" command line binary is not present on the system (or any other number of software libraries that also have optional command line binaries).  I would simply skip that portion of the test if mdb_stat is not found.

**Comment by nicowilliams** [comment]
`mdb_stat` is needed only for a sanity check which we don't do in other cases.  It's nice, but hardly necessary.

The simplest fix here is to ignore errors from the invocation of `mdb_stat` in `tests/kdc/check-iprop.in`; the best thing to do would be to check if it's available either in that script (but how to do that portably with the POSIX shell?) or in `configure.ac`.
