### ISSUE TITLE
Heimdal shouldn't bundle out-of-date libtommath

### ISSUE THREAD

**Issue by brianmay** [heimdal/heimdal#273]
Hello,

I believe Heimdal is using a version of libtommath from 2010. I see that Redhat took up this issue in 2014:

* https://bugzilla.redhat.com/show_bug.cgi?id=1118462
* https://pagure.io/packaging-committee/issue/387

Since then, the one remaining obstacle was removed (see https://github.com/libtom/libtommath/pull/69#issuecomment-293423126).

Are there any further issues preventing Heimdal from using the system installed version of libtommath?

The upstream libtommath maintainer thinks that they might have a better fix for the x32 issue, then
what was merged in 005c8886d7fab4eacc2a54f80b777874934c6cf4.

Thanks

**Comment by sjaeckel** [comment]
> The upstream libtommath maintainer thinks that they might have a better fix for the x32 issue, then
what was merged in 005c888.

c.f. point 2 @ https://github.com/libtom/libtommath/pull/69#issuecomment-293209612

FYI the x32 build is also already building fine for master, but I think it'd be better to test on develop as there are already several bugs fixed. I'll do a new release then after your testing.

**Comment by nicowilliams** [comment]
I thought @vdukhovni had updated libtommath in `master` recently.

**Comment by vdukhovni** [comment]
I have figured out how to and tested an updated libtommath, but have not yet pushed that to master...

**Comment by nicowilliams** [comment]
@vdukhovni Maybe we should treat `libtommath` like `libedit` and `SQLite3`, and autodetect its presence/absence.

**Comment by sjaeckel** [comment]
any progress on that?
