### ISSUE TITLE
SONAME bump for libroken

### ISSUE THREAD

**Issue by brianmay** [heimdal/heimdal#279]
Hello,

In the fix for #107, two symbols were renamed in libroken.

However the SONAME was never incremented for the next release.

This causes problems for distributions such as Debian in getting upgrades to work smoothly.

Can you please increment the SONAME for libroken?

Thanks

**Comment by nicowilliams** [comment]
We really should have an automatic system for detecting the need to make a SONAME version change...

**Comment by nicowilliams** [comment]
I guess I'm somewhat keen on not having a build dependency on git itself.  It is nice to be able to do a shallow clone in the process of building.  OTOH, maintainers can be expected to use git and have full clones.  But CI builds would also need deeper clones.

**Comment by jaltman** [comment]
Bump SONAME for 8.0
