### ISSUE TITLE
principal.c:1253:18: warning: logical 'or' of collectively exhaustive tests is always true [-Wlogical-op]

### ISSUE THREAD

**Issue by dcb314** [heimdal/heimdal#282]
Source code is

   if (c >= 'A' || c <= 'Z')

Maybe better code

   if (c >= 'A' && c <= 'Z')

**Comment by elric1** [comment]
If you submit a pull request, I'll merge it.

**Comment by dcb314** [comment]
Sorry, no pull request. You might want to add gcc compiler
flag -Wlogical-op to your Linux builds to make this kind
of error more visible in future.

**Comment by nicowilliams** [comment]
> If you submit a pull request, I'll merge it.

I'll fix it.

**Comment by elric1** [comment]
@dcb314: no worries, I'll do it.  I thought that I'd offer you the opportunity to do it as some people like to put their name on the commits that they suggest.

**Comment by elric1** [comment]
Closed by PR#283
