### ISSUE TITLE
Download links on home page gives HTTP 404

### ISSUE THREAD

**Issue by mbakke** [heimdal/heimdal#304]
Steps to reproduce:

1. Go to <https://h5l.org/releases.html?show=7.4.0>.
2. Click tarball link.

**Comment by quanah** [comment]
Thanks! The releases page points to the old site.  I'll work on getting it tweaked to work like it does off the main page.

**Comment by quanah** [comment]
Going to close this issue for the one correctly filed for the website (https://github.com/heimdal/h5lweb/issues/25)
