### ISSUE TITLE
Solaris 10: libedit uses getline

### ISSUE THREAD

**Issue by quanah** [heimdal/heimdal#309]
libedit uses getline.  If the host OS doesn't have it, it does this declaration:

```
#ifndef HAVE_GETLINE
#define getline libedit_getline
ssize_t getline(char **line, size_t *len, FILE *fp);
#endif
```

However, there is no libedit_getline function anywhere in the code base, so you end up with an unresolved symbol while linking, breaking the build.  One option would be to replace getline with fputs.

**Comment by nicowilliams** [comment]
On Thu, Aug 03, 2017 at 06:28:18PM -0700, Quanah Gibson-Mount wrote:
> libedit uses getline.  If the host OS doesn't have it, it does this declaration:
> 
> ```
> #ifndef HAVE_GETLINE
> #define getline libedit_getline
> ssize_t getline(char **line, size_t *len, FILE *fp);
> #endif
> ```
> 
> However, there is no libedit_getline function anywhere in the code
> base, so you end up with an unresolved symbol while linking, breaking
> the build.  One option would be to replace getline with fputs.

Oh, there's no definition for this function.  I think you meant fgets()
instead of fputs(), but no, that's not OK.  We just need to include a
definition.  I suspect libeditline has one, and it just wasn't included
in Heimdal's copy.

**Comment by nicowilliams** [comment]
Here's a libedit with a private fgetln():

https://github.com/cdesjardins/libedit/blob/18b682734c11a2bd0a9911690fca522c96079712/src/fgetln.c

**Comment by quanah** [comment]
Ok.  I'm checking out the netbsd libedit source as well, as that's the canonical source, to see what they have.

**Comment by quanah** [comment]
Apple has some options at https://opensource.apple.com//source/cvs/cvs-42/cvs/lib/ as well, but it is GPLv2, not sure if that works for Heimdal.

Or https://trac.macports.org/browser/trunk/dports/textproc/uni2ascii/files/patch-ascii2uni.c.diff?rev=73852

also GPLv2.  I'll play with the fgetln() one instead.

**Comment by quanah** [comment]
also, netbsd didn't have anything I could find in their source, at least not under libedit.

**Comment by quanah** [comment]
Here's a free getline: https://github.com/cfengine/core/blob/master/libcompat/getline.c
