### ISSUE TITLE
krb5_get_init_creds_opt_set_change_password_prompt incomplete

### ISSUE THREAD

**Issue by rra** [heimdal/heimdal#322]
In 7422cd1f6 `krb5_get_init_creds_opt_set_change_password_prompt` was added. Unfortunately, it doesn't work (causing the pam-krb5 test suite to break) because it doesn't catch all of the places where the password change prompt is shown. It modified the fallback code at the end of `krb5_get_init_creds_password` to call `change_password`, but the normal password change is kicked off here:

https://github.com/heimdal/heimdal/blob/master/lib/krb5/init_creds_pw.c#L2381

The same check needs to be done here, but unfortunately it doesn't look like the init_creds options are passed down this far.  Or perhaps this password change logic should be deleted in favor of always using the code that handles the return value of `krb5_init_creds_get`?  I can submit a patch, but I'm not sure the correct fix.

(cc @spaceone)

**Comment by lhoward** [comment]
Removing the password change code from `krb5_init_creds_step()` looks like the right solution to me. MIT handles password expiry at a higher level, in `krb5_get_init_creds_password()` (as Heimdal does also). It could be an issue if we ever implement IAKERB but MIT doesn't handle password changes within IAKERB either, as far as I can tell. Patch coming up.

**Comment by lhoward** [comment]
@rra please let me know if this fixes your issue

**Comment by lhoward** [comment]
Hmm, this may break some tests. Investigating.

**Comment by lhoward** [comment]
Need to revist: kinit uses `krb5_init_creds_get()` directly so removing this code breaks it. Will fix tomorrow.

**Comment by lhoward** [comment]
OK, try new patch.

**Comment by lhoward** [comment]
Merged in 070d0cf
