### ISSUE TITLE
libtommath: bundled or system installed version?

### ISSUE THREAD

**Issue by sfhacker** [heimdal/heimdal#324]
Building the master branch of Heimdal using our system installed version of libtommath (1.0), we get the following linking error:

./.libs/libhcrypto.a(libhcrypto_la-rsa-ltm.o):rsa-ltm.c:(.text+0x279): undefined reference to `mp_find_prime'
./.libs/libhcrypto.a(libhcrypto_la-rsa-ltm.o):rsa-ltm.c:(.text+0x3cf): undefined reference to `mp_find_prime'

Please, advise how to proceed.

Cheers.

**Comment by quanah** [comment]
see also #273

**Comment by jaltman** [comment]
#273

**Comment by lhoward** [comment]
`mp_find_prime()` is a function added by Love that is not upstream. We could open a PR to add it upstream and/or you can build this file separately.

**Comment by lhoward** [comment]
I've opened a PR to submit `mp_find_prime()` upstream ( It looks however that the libtommath API has changed a bit since the version included in Heimdal, so we would need to weigh the cost of possibly supporting multiple versions versus continuing to bundle a known working version. See libtom/libtommath#482.

**Comment by sfhacker** [comment]
The lethargic period is over! Thanks be to God.
We are about to produce a new Windows release (server & client) from source. Perhaps we should wait for ...... who knows?

Thanks anyway.

**Comment by lhoward** [comment]
If you're producing a release, best to do from a tagged release (@jaltman can advise further).

**Comment by lhoward** [comment]
If you need to work around the `mp_find_prime()` issue specifically then you can do this:

```diff
diff --git a/lib/hcrypto/rsa-ltm.c b/lib/hcrypto/rsa-ltm.c
index 4ac5617cb..803da1d23 100644
--- a/lib/hcrypto/rsa-ltm.c
+++ b/lib/hcrypto/rsa-ltm.c
@@ -536,7 +536,7 @@ ltm_rsa_generate_key(RSA *rsa, int bits, BIGNUM *e, BN_GENCB *cb)
     do {
        BN_GENCB_call(cb, 2, counter++);
        CHECK(random_num(&p, bitsp), 0);
-       CHECK(mp_find_prime(&p,128), MP_YES);
+       CHECK(mp_prime_next_prime(&p,128,0), MP_OKAY);
 
        mp_sub_d(&p, 1, &t1);
        mp_gcd(&t1, &el, &t2);
@@ -548,7 +548,7 @@ ltm_rsa_generate_key(RSA *rsa, int bits, BIGNUM *e, BN_GENCB *cb)
     do {
        BN_GENCB_call(cb, 2, counter++);
        CHECK(random_num(&q, bits - bitsp), 0);
-       CHECK(mp_find_prime(&q,128), MP_YES);
+       CHECK(mp_prime_next_prime(&q,128,0), MP_OKAY);
 
        if (mp_cmp(&p, &q) == 0) /* don't let p and q be the same */
            continue;
```
