### ISSUE TITLE
[Master Branch] Build and Test Report

### ISSUE THREAD

**Issue by sfhacker** [heimdal/heimdal#325]
**Environment**:
    - Windows
    - GCC 6.3.0 (x86_64)
    - OpenSSL 1.1.1 (TLS 1.3)
    - LibTomMath 1.0
	
# Tests

**lib/roken**

TOTAL: 14
PASS:  12
SKIP:  1
XFAIL: 0
FAIL:  1    [ resolve-test ]
XPASS: 0
ERROR: 0

**lib/base**

TOTAL: 1
PASS:  1
SKIP:  0
XFAIL: 0
FAIL:  0
XPASS: 0
ERROR: 0

**lib/sl**

TOTAL: 1
PASS:  1
SKIP:  0
XFAIL: 0
FAIL:  0
XPASS: 0
ERROR: 0

**lib/wind**

TOTAL: 8
PASS:  8
SKIP:  0
XFAIL: 0
FAIL:  0
XPASS: 0
ERROR: 0

**lib/asn1**

TOTAL: 5
PASS:  5
SKIP:  0
XFAIL: 0
FAIL:  0
XPASS: 0
ERROR: 0

**lib/hcrypto**

TOTAL: 12
PASS:  11
SKIP:  0
XFAIL: 0
FAIL:  1     [ test_crypto: failed to private encrypt: 20 0 ]
XPASS: 0
ERROR: 0

**lib/hx509**

TOTAL: 16
PASS:  12
SKIP:  1     [ test_nist2 ]
XFAIL: 0
FAIL:  3     [ test_ca test_pkcs11 test_windows ]
XPASS: 0
ERROR: 0

                test_ca: hx509_ca_sign_self: RSA private encrypt failed: 569888
		test_windows: no CA certificate found: Certificate not found
   
**lib/krb5**

TOTAL: 25
PASS:  25
SKIP:  0
XFAIL: 0
FAIL:  0
XPASS: 0
ERROR: 0

**lib/ntlm**

TOTAL: 1
PASS:  1
SKIP:  0
XFAIL: 0
FAIL:  0
XPASS: 0
ERROR: 0

**lib/gssapi**

TOTAL: 3
PASS:  3
SKIP:  0
XFAIL: 0
FAIL:  0
XPASS: 0
ERROR: 0

**lib/hdb**

PASS: test_dbinfo
PASS: test_hdbkeys
PASS: test_mkey
PASS: test_hdbplugin

**lib/kadm5**

PASS: ipropd-master
PASS: ipropd-slave
PASS: test_pw_quality
PASS: iprop-log

**lib/otp**

PASS: otptest

**tests/db**

TOTAL: 4
PASS:  3
SKIP:  0
XFAIL: 0
FAIL:  1
XPASS: 0
ERROR: 0

**tests/can**

TOTAL: 1
PASS:  0
SKIP:  0
XFAIL: 0
FAIL:  1
XPASS: 0
ERROR: 0

**tests/gss**

TOTAL: 6
PASS:  5
SKIP:  0
XFAIL: 0
FAIL:  1      [ check-gssmask ]
XPASS: 0
ERROR: 0

**tests/kdc**

TOTAL: 18
PASS:  14
SKIP:  1
XFAIL: 0
FAIL:  3
XPASS: 0
ERROR: 0

Any assistance with the failing tests would be grateful.
More to come.

Thanks.

**Comment by sfhacker** [comment]
A quick update:

* resolve-test is passing now: some issue with a variable not being defined.
* test_pkcs11 succeeds! Wrong declaration in a header file.
*  check-gssmask is also passing now:
...
...
n1 connects to self using host/n1.test.h5l.se@TEST.H5L.SE
n2 connects to self using host/n2.test.h5l.se@TEST.H5L.SE
n3 connects to self using host/n3.test.h5l.se@TEST.H5L.SE
"All" permutation tests
n2 -> n3
        n3 -> n1
                n1 -> n2
n2 -> n1
        n1 -> n3
                n3 -> n2
n3 -> n1
        n1 -> n2
                n2 -> n3
n3 -> n2
        n2 -> n1
                n1 -> n3
n1 -> n3
        n3 -> n2
                n2 -> n1
n1 -> n2
        n2 -> n3
                n3 -> n1
sending goodbye and waiting for log sockets
done

Thanks.

**Comment by jaltman** [comment]
#125
