### ISSUE TITLE
Heimdal ktutil cannot handle aes256-cts keys

### ISSUE THREAD

**Issue by quanah** [heimdal/heimdal#356]
In working in configuring SASL/GSSAPI on a server the other day, I ran into the issue that it was unsuccessful because the aes256-cts key for the principal was missing from the keytab for the ldap/* principal, while it was there for the host/* principal.  The difference was that the host/* principal had been added to the keytab via MIT kerberos based binaries, and the ldap/* principal was added via Heimdal's ktutil.  After a bit of searching, I came across this [gem](https://kb.iu.edu/d/aumh) :

```
If the keytab created in Heimdal does not work, it is possible you will need an aes256-cts entry. In that case, you will need to find a computer with MIT Kerberos, and use that method instead
```

Switching to MIT binaries to get the ldap/* principal from the KDC resolved the issue.  The KDC in this instance was Active Directory.

This is a serious issue for sites where the security policies require this key strength.  It should be possible to do this via the Heimdal ktutil.

Version in question is Heimdal 7.4.0.

**Comment by nicowilliams** [comment]
@quanah We use aes256 keys all the time, and `ktutilt` seems to work fine with aes256 keys.

Can you give us more detail, and maybe an example, of what's not working?

**Comment by nicowilliams** [comment]
So, just in case, I attempted to replicate this with Heimdal and MIT:

```
$ build/admin/ktutil -k /tmp/kth add -p username@ADS.IU.EDU -V 1 -e aes256-cts
2017-12-13T14:44:37 error message: Did not find a plugin for ccache_ops: 2
Password:
Verify password - Password:
$ /tmp/mit/bin/ktutil
ktutil:  rkt /tmp/kth
ktutil:  l -e -k
slot KVNO Principal
---- ---- ---------------------------------------------------------------------
   1    1                      username@ADS.IU.EDU (aes256-cts-hmac-sha1-96)  (0xd474d941e0c2961a560c0b4fc1a07bba0e5364152b508428f74093faf27ba0b3)
ktutil:  clear
ktutil:  l -e -k
slot KVNO Principal
---- ---- ---------------------------------------------------------------------
ktutil:  addent -password -p username@ADS.IU.EDU -k 1 -e aes256-cts
Password for username@ADS.IU.EDU:
ktutil:  l -e -k
slot KVNO Principal
---- ---- ---------------------------------------------------------------------
   1    1                      username@ADS.IU.EDU (aes256-cts-hmac-sha1-96)  (0xd474d941e0c2961a560c0b4fc1a07bba0e5364152b508428f74093faf27ba0b3)
ktutil:  ^D$ 
```

As you can see, both MIT and Heimdal are able to create the *same* keytab entries for the same principal using the same password and the same enctype.  The password I used was `foo`, and the principal name above came from the example in the page you linked.

Perhaps the page you linked refers to a very old Heimdal release?  Certainly it can't be referring to 7.x, I don't think.

I'm closing this.  Feel free to re-open if there is something I missed.
