### ISSUE TITLE
configure search for libedit's readline.h fails on Fedora

### ISSUE THREAD

**Issue by ktdreyer** [heimdal/heimdal#38]
When building against Fedora's system libedit library, the Heimdal autoconf macro fails to find libedit's `readline.h`.

I've installed libedit-devel, which ships `/usr/include/editline/readline.h`. The autoconf macro in Heimdal's `configure.ac` only searches for `readline.h` and `readline/readline.h`. I think it should search for `editline/readline.h`.

Here's the relevant configure output, when using `--with-libedit=/usr` :

```
checking for readline... no
checking for libedit... checking readline.h usability... no
checking readline.h presence... no
checking for readline.h... no
checking readline/readline.h usability... no
checking readline/readline.h presence... no
checking for readline/readline.h... no
headers /usr/include, libraries /usr/lib
checking for hesiod... no
```

**Comment by nicowilliams** [comment]
This looks like a very simple fix, though the very simple fix doesn't seem to be doing it for me.  Perhaps the `rk_TEST_PACKAGE` m4 macro is broken.
