### ISSUE TITLE
Example hx509 certificate generation no longer works with OpenSSL 1.1.0

### ISSUE THREAD

**Issue by madscientist159** [heimdal/heimdal#392]
The example OpenSSL configuration file in heimdal/lib/hx509/data/openssl.cnf throws an OID exception as of OpenSSL 1.1.0:

```
problem creating object uid=1.3.6.1.5.2.3.5
139834758264064:error:08064066:object identifier routines:OBJ_create:oid exists:../crypto/objects/obj_dat.c:689:
```

**Comment by madscientist159** [comment]
Digging further, it looks like OpenSSL 1.1.0 and above have common OIDs already built in.  Therefore, the new_oid section may not be needed to reference this common OID.

**Comment by jaltman** [comment]
@lhoward are you willing to work on this issue?

**Comment by lhoward** [comment]
This just appears to be an example: gen-req.sh (which references openssl.cnf) is not actually used by hx509 or its test suite. So I propose we just update openssl.cnf commenting out the OID definition, with a note that versions prior to OpenSSL 1.1.0 will require the OID to be defined.

**Comment by lhoward** [comment]
(Please correct me if I am wrong.)

**Comment by lhoward** [comment]
OK, I will modify gen-req.sh to dynamically detect the version of OpenSSL and use the appropriate configuration file.

**Comment by lhoward** [comment]
workaround added in 6561aff
