### ISSUE TITLE
--with-db-type-preference= does not fix the build error in LibreElec 8.2.4

### ISSUE THREAD

**Issue by Golffies** [heimdal/heimdal#396]
Commit 02770ce should have solved [that specific build error](https://github.com/maximeh/buildroot/commit/02770ce47d6c358c959410e87c5218170d2e08e7). 

Oddly enough, we are still getting [the exact same error](https://forum.libreelec.tv/thread/12926-libreelec-i686-32bits-build-heimdal-7-4-error/) when compiling heimdal 7.4.0 as [included into LibreELec 8.2.4](https://github.com/LibreELEC/LibreELEC.tv/tree/8.2.4) and targetting i686 platform.

LibreElec is a HTPC/PVR dedicated distribution, not supporting any more i686. We were trying to adapt it and compile for i686 when we eventually got stuck by this build error, which we did not find a workaround for. More details are available through the upper link to the LibreElec forum.

**Comment by jaltman** [comment]
68687ecf6eff2e66d878a4b0d76eebc2a67a7e23 is the change that altered --with-db-type-preference=list to require list of databases but your commit 02770ce doesn't provide a list.

**Comment by Golffies** [comment]
Hi Jeffrey,
Thank you for stepping in.

I linked to commit [02770ce from buildroot](https://github.com/maximeh/buildroot/commit/02770ce47d6c358c959410e87c5218170d2e08e7), because it pictures the very same error than the one we are encountering with our build of Heimdal, from version 7.4.0, as explained earlier.

My point here is : why are we facing in 7.4.0 that same error, which seems to have been fixed already by 68687ec ?

Regards.

**Comment by MilhouseVH** [comment]
Is the issue with `--with-db-type-preference` or OTP support (enabled by default)? The errors you posted to the LibreELEC forum would suggest the latter.

LibreELEC 9.0 has [this commit](https://github.com/LibreELEC/LibreELEC.tv/commit/70f62dad6330091b0d91c49535d438ff6c22f0fe) which disables OTP and is able to build heimdal 7.5.0 (and, previously, 7.4.0) without issue.

If a value must be specified for `--with-db-type-preference` then heimdal should abort during `configure` if null is supplied. And if a null value for `--with-db-type-preference` is supported, then heimdal should disable OTP (which is dependent on a database) rather than fail when trying build with OTP support.

**Comment by priyapraburam26** [comment]
@MilhouseVH Thank you so much. Adding --disable-otp \ worked! :+1:

**Comment by priyapraburam26** [comment]
@MilhouseVH Although that worked, the final build isn't happening.
There's some problem with linking of libraries.
This is what it says:
Any idea why it isn't working?

> build/dbwrappers/dbwrappers.a(sqlitedataset.cpp.o):sqlitedataset.cpp:function dbiplus::SqliteDatabase::copy(char const*): error: undefined reference to 'sqlite3_backup_init'
build/dbwrappers/dbwrappers.a(sqlitedataset.cpp.o):sqlitedataset.cpp:function dbiplus::SqliteDatabase::copy(char const*): error: undefined reference to 'sqlite3_backup_step'
build/dbwrappers/dbwrappers.a(sqlitedataset.cpp.o):sqlitedataset.cpp:function dbiplus::SqliteDatabase::copy(char const*): error: undefined reference to 'sqlite3_backup_finish'
collect2: error: ld returned 1 exit status

**Comment by MilhouseVH** [comment]
@priyapraburam26 I'm not sure to be honest, and I can't really tell much at all from your log snippet.

I've never had a problem building heimdal 7.4.0 or 7.5.0 on Ubuntu 17.10, with/without the OTP workaround. The OTP issue only became a problem when building with Arch, so there's possibly an issue with the LibreELEC build system and/or your particular build host when cross-compiling.

I think you should take this to the LibreELEC forum for further discussion (use the [existing thread](https://forum.libreelec.tv/thread/12926-libreelec-i686-32bits-build-heimdal-7-4-error/)) as further discussion is not relevant to Heimdal and it's subscribed github users until we know more.

Note that LibreELEC 8.2 is end-of-life and no longer actively developed - the focus now is on LibreELEC 9.0 (Kodi 18 etc.) so try building LibreELEC `master` which is based on heimdal 7.5.0 with the OTP workaround.

Before reporting any issues with the build always build "clean" - that is, remove the `build.LibreELEC-*` folder and build, as some packages can confuse an incremental build whenever package options are changed.

If you still have a build issue, please post as much detail as possible on the LibreELEC forum.

**Comment by nicowilliams** [comment]
I mean, if you have no preference, then don't use `--with-db-type-preference=`.  Doesn't that work?

**Comment by MilhouseVH** [comment]
@nicowilliams yes, removing `--with-db-type-preference=` (but keeping `--disable-otp`) works with Ubuntu 17.10, and we should have dropped `--with-db-type-preference=` when adding `--disable-otp`. Thanks for the tip. I've pushed [a PR](https://github.com/LibreELEC/LibreELEC.tv/pull/3167) which drops the db-type setting, assuming there are no build complications on Arch.

**Comment by jaltman** [comment]
@MilhouseVH I am going to close this request.
