### ISSUE TITLE
Merge Kerberos account synchronization plugin patch

### ISSUE THREAD

**Issue by macrotex** [heimdal/heimdal#397]
Merge into the Heimdal kadmin libraries code that supports the krb5-sync plugin that synchronizes Kerberos passwords and account enabling/disabling with an Active Directory.

From the patch documentation:

> The patches in this directory apply to Heimdal and add plugin support to the kadmin libraries for performing actions before and after a password change is committed to the KDC database and after a change is made to the attributes of a principal (specifically, a change to DISALLOW_ALL_TIX).

The source code and documentation is here: https://git.eyrie.org/git/kerberos/krb5-sync.git

Note that this issue is asking _only_ to integrate the plugin code into the Heimdal kadmin code. Patches for previous versions of Heimdal, as well as documentation, is in the `patches/` directory of the Git repository referenced above.

**Comment by jaltman** [comment]
The upstream repository is forked as https://github.com/heimdal/krb5-sync.   The master branch was updated for Heimdal 7.4.

**Comment by lhoward** [comment]
The patch doesn't implement the delete, randkey, or rename hooks. Should these be implemented before merging?

Also, it has some bugs (which I will fix); postcommit hooks shouldn't trample on the return code.

**Comment by lhoward** [comment]
Is it OK to change the plugin ABI? I'm happy to leave as-is, but it seems like if the post-commit hooks are going to get called irrespective of update success, then they should also be passed the return value of kadm5_log_modify()

**Comment by macrotex** [comment]
> 
> 
> The patch doesn't implement the delete, randkey, or rename hooks. Should these be implemented before merging?
> 
> Also, it has some bugs (which I will fix); postcommit hooks shouldn't trample on the return code.

I don't mind supporting hooks for the additional actions, but all I really need are the add and change password hooks. It's up to you.

**Comment by jaltman** [comment]
@lhoward for completeness please implement delete, randkey and renamke hooks.

**Comment by lhoward** [comment]
Fixed in master
