### ISSUE TITLE
Missing make headers

### ISSUE THREAD

**Issue by timokau** [heimdal/heimdal#398]
Since the 7.5.0 update, the [nix](https://github.com/nixos/nixpkgs) package applies a patch to heimdal that adds two headers to the makefile:

```
--- a/lib/hx509/Makefile.am 2018-03-21 15:41:38.622968809 +0100
+++ b/lib/hx509/Makefile.am 2018-03-21 15:41:32.655162197 +0100
@@ -9,6 +9,8 @@
	sel-gram.h			\
	$(gen_files_ocsp:.x=.c)		\
	$(gen_files_pkcs10:.x=.c)	\
+	ocsp_asn1.h			\
+	pkcs10_asn1.h			\
	hx509_err.c			\
	hx509_err.h
```

Without this patch, the build fails:

```
  #include <ocsp_asn1.h>
            ^~~~~~~~~~~~~
  compilation terminated.
  make[3]: *** [Makefile:1321: hxtool.o] Error 1
  make[3]: Leaving directory '/build/source/lib/hx509'
  make[2]: *** [Makefile:1099: all] Error 2
  make[2]: Leaving directory '/build/source/lib/hx509'
  make[1]: *** [Makefile:564: all-recursive] Error 1
  make[1]: Leaving directory '/build/source/lib'
  make: *** [Makefile:611: all-recursive] Error 1
```

**Comment by jaltman** [comment]
It is unclear from your report.  Is the build of Heimdal 7.5.0 itself failing or of nix?

On which operating system is the failure?

**Comment by timokau** [comment]
`nix` is a package manager that includes Heimdal. The build receipt includes that patch which I just noticed when trying to fix another error. Building without the patch fails. The OS is `NixOS`.

**Comment by antekone** [comment]
Without this patch the build also fails on ArchLinux. Adding those two lines fixes the build.

**Comment by lhoward** [comment]
Believe this may have been fixed by 572a6fd7, can you please test with master and reopen if necessary?

**Comment by timokau** [comment]
I can confirm that this issue is fixed. Thanks!

**Comment by lhoward** [comment]
Great! Thanks for checking!
