### ISSUE TITLE
Provide profile.h

### ISSUE THREAD

**Issue by Arfrever** [heimdal/heimdal#402]
Keyutils since https://git.kernel.org/pub/scm/linux/kernel/git/dhowells/keyutils.git/commit/?id=0d71523ab58493e1b40e1c80d569ff8ebc5ea27d needs `profile.h` header (with at least type `profile_t` and functions: `profile_init`, `profile_get_subsection_names`, `profile_get_boolean`, `profile_get_values` and `error_message`).

**Comment by jaltman** [comment]
The MIT profile library is a public interface whereas Heimdal does not provide a public interface for manipulating configuration files.  

David Howells has modified his keyutils so that it no longer depends on MIT's profile library.
