### ISSUE TITLE
NTLM version formatting is incorrect.

### ISSUE THREAD

**Issue by Sushant-M** [heimdal/heimdal#404]
The NTLM revision should be 00 00 00 0F
which translates to NTLMRevisionCurrent = 15
In the present case the produced result is 0F 00 00 00
The reserved field is incorrectly filled with 0F 00 00 and the NTLMReivisonCurrent = 0

The function encode_os_version in file ntlm.c needs to be changed to accommodate this.

**Comment by jaltman** [comment]
Confirmed https://msdn.microsoft.com/en-us/library/cc236654.aspx

**Comment by Sushant-M** [comment]
I'll fix it and submit a pull request by tomorrow.
