### ISSUE TITLE
Mailing lists

### ISSUE THREAD

**Issue by r4nd0m123** [heimdal/heimdal#438]
Hi,

I had a configuration question and thought that it would be more suitable on a mailing list, but I received a bounce back when trying to register. Are the mailing lists defunct?

Thanks

**Comment by quanah** [comment]
Which mailing list were you attempting to subscribe to?  They certainly work.  Here's the link to the heimdal-discuss list to subscribe: https://www.h5l.org/mailman/listinfo/heimdal-discuss
