### ISSUE TITLE
Request: Support aliases for client principal initial ticket acquisition

### ISSUE THREAD

**Issue by jaltman** [heimdal/heimdal#452]
Heimdal permits aliases to be assigned to client principals but the alias name cannot be used for initial ticket acquisition.

**Comment by jaltman** [comment]
@nicowilliams has suggested using PA-TGS in AS-REQs

**Comment by lhoward** [comment]
Isn’t this a bug in the implementation of the referrals draft rather than a new feature? I may be missing context.

**Comment by lhoward** [comment]
@jaltman do you want AS-REQ aliases (sans name canonicalisation) to be on by default, or do you want a knob?

**Comment by jaltman** [comment]
I cannot think of a reason why this functionality should be off by default or otherwise.

**Comment by nicowilliams** [comment]
Hard aliases == you use the alias in the `AS-REQ` and you get a TGT for the alias name.

Soft aliases == you use the alias in the `AS-REQ` and you get a TGT for the canonical name.

?

If so, I agree.

In the hard alias case you'd have to get the non-default salt in the `ETYPE-INFO`.  In the soft alias case you get to use the default salt.

There's no referrals codepaths in the AS-REQ case, thank goodness.  That's all TGS stuff and is pretty complex in both, Heimdal and MIT :(

I do like the idea that you can grant one principal the ability to get TGTs for another using `PA-TGS` in an `AS-REQ`.

**Comment by jaltman** [comment]
@nicowilliams using your terminology, the case I'm concerned with is the hard alias case.   I believe the soft alias case requires that the client explicitly request canonicalization.  Today's clients will reject any response with a name other than the AS-REQ specified name unless canonicalization has been requested.

I'm trying to reduce the work for an organization that needs to rename their realm from FOO.COM to BAR.COM .   By adding user@BAR.COM as an alias to the user@FOO.COM client principal entry, the end user should be able to switch to authenticating as user@BAR.COM without requiring any rekeying.

Its then up to the application service administrators to configure their systems to accept one or both of user@FOO.COM and user@BAR.COM at various stages of the transition.

**Comment by nicowilliams** [comment]
@jaltman It might be interesting to have a realm alias feature for that use case -- it would be easier to deploy for your specific use case.  AD has it, sort of, by supporting all case combinations of a realm as hard aliases of the realm.

**Comment by jaltman** [comment]
Something I noticed today is that Heimdal kinit squashes the --canonicalize and --enterprise options together.  Is this correct?

Isn't there an important difference between the two?   For the --enterprise case there is at most one component and therefore the logic in krb5_parse_name_flags() is correct.  However, for the --canonicalize case is there a single component requirement?

I question the generation of principal `user\@FOO.COM@BAR.COM` when processing the command `kinit --canonicalize user@FOO.COM` as opposed to `kinit --enterprise user@FOO.COM`.  Shouldn't the `--canonicalize` case result in `user@FOO.COM` being the requested principal?

**Comment by jaltman** [comment]
@nicowilliams A realm alias or case-insensitive realm aliasing case might be very interesting.   I still want the per principal aliasing to work in my situation.

**Comment by nicowilliams** [comment]
@jaltman Sure.  More options here is better.  I was just thinking that for a realm rename exercise a realm alias feature would be much easier to deploy.

**Comment by lhoward** [comment]
The "hard alias" may create issues with services that do name-based authorisation. We could return AD-LOGIN-ALIAS from RFC6806 but (unlike MIT) we don't have an implementation of GSS naming attributes, so it's not clear how we would surface aliases to the application.

**Comment by lhoward** [comment]
For the purposes of this feature request, I am going to focus on adding support for hard aliases using the default DB backend.

**Comment by lhoward** [comment]
If trivial, I will also verify support for name canonicalisation (soft) aliases.

**Comment by lhoward** [comment]
The reason that --canonicalize implies --enterprise in kinit I believe is a convenience, to do with the way HDB handles aliases in the simple (dumb database, not Samba or other directory service backend).

If I do `kinit --canonicalize user@FOO.COM` then kinit request a TGS of `krbtgt/FOO.COM@FOO.COM`. This will fail if the canonical realm is BAR.COM, of course. 

Now: I am relying on memory here, which is approximately 10 years old, but: Windows clients will always use enterprise names when doing AS-REQs on behalf of an end-user, so this is a non-issue (enterprise principal names/UPNs imply canonicalisation). I also believe Windows will treat an enterprise principal name that is presented as a normal name (i.e. with the RHS of the enterprise name as the realm) as if it were an enterprise principal name. I'm reluctant to add that logic to the AS-REQ KDC path in Heimdal, as it's complicated enough already, and I believe that if the primary use case is Windows interoperability it is likely working today and shouldn't be touched.

Rather, I'd prefer to support Jeff's "hard alias" case by explicitly requiring a TGS name alias. (I'm yet to test this, but I would plan to fix anything that breaks.)

**Comment by lhoward** [comment]
Hmm, I think we want to have a KDC-side option for enabling aliases without canonicalization. I'm concerned about breaking something for Samba. Either that, or we have a new HDB flag that is private between the AS path and the "dumb" HDB backends (e.g. HDB_F_ALIAS_OK).

**Comment by lhoward** [comment]
Jeff: I did want to check though, for your use case, are you expecting your clients won't be sending the canonicalize flag?

**Comment by nicowilliams** [comment]
I agree that no canonicalize flag -> hard alias, canonicalize set -> soft alias.  And that soft is better.

**Comment by lhoward** [comment]
Fixed in e11abf4.
