### ISSUE TITLE
ipropd-master should fork to serve full props

### ISSUE THREAD

**Issue by nicowilliams** [heimdal/heimdal#455]
`ipropd-master` is not C10K and does not perform async I/O.  If writes to a socket hang, then `ipropd-master` will become non-responsive.  If full-props take a long time, then `ipropd-master` will appear to be non-responsive during them, and it can only perform one at a time, which can cause more full props to be needed.

`ipropd-master` could `fork(2)` a child for each connection.  To do so would require re-writing the `write_stats()` code, as rather than write the stats for all peers, it would have to update the stats file with just one peer's stats.  Or else each child process should send updates to the parent which would then keep `write_stats()` as it is.

**Comment by nicowilliams** [comment]
If a slave reconnects, then the parent `ipropd-master` would have to kill the existing child for that slave.

**Comment by macrotex** [comment]
This is an important feature in those situations where slaves are replicating from scratch and, for whatever reason, the replication takes a long time. For example, assume there are two slaves A and B.  If A needs to do a complete re-sync and takes a very long time, slave B will eventually get tired of waiting and insist on its own re-sync when it finally gets the attention of the master. But if B also takes a long time to re-sync A gets blocked and does a re-sync when it gets the attention of the master. And so on, each slave forever doing a complete re-sync. (This is in fact happening with us now with version 7.5; we have mitigated this by setting timelost to an hour.)

Less problematic, but still a problem, is when slave A is doing a complete re-sync and is taking a long time. All the other slaves don't get updates meaning that passwords are not in sync. Of course, in this case the client should try again with the master, but we prefer to keep the load off of the master as much as possible.

**Comment by elric1** [comment]
Isn't this solved in 0334472ab5a0 ? ipropd-master has been made async which isn't fork(2)ing but solves the actual issue raised here.
