### ISSUE TITLE
NegoEx support

### ISSUE THREAD

**Issue by lhoward** [heimdal/heimdal#470]
I just BSD relicensed my NegoEx implementation for MIT – https://github.com/krb5/krb5/pull/883/files

Maybe someone wants to port it to Heimdal someday.

**Comment by nicowilliams** [comment]
@lhoward How important is NegoEx for interop?

**Comment by lhoward** [comment]
On the feature side, it's nice because it lets you exchange some metadata about credentials before committing to a mechanism.

On the actual interoperability side, it would have resolved an issue with the EAP SSP which forced us to preference EAP ahead of NTLM (Windows, at least from Windows 8 onwards, doesn't really like negotiating mechanisms with SPNEGO other than NTLM and Kerberos).

I believe all newer Microsoft mechanisms from and including PKU2U can only be negotiated using it.

**Comment by lhoward** [comment]
Fixed in #668
