### ISSUE TITLE
Make --keepold and prune-key-history enabled by default in Heimdal 8

### ISSUE THREAD

**Issue by nicowilliams** [heimdal/heimdal#477]
Given that we have the ability to prune key history (old keys not needed to decrypt potentially still-extant tickets) at `cpw`/`randkey`/`setkeys` time, maybe we should enable that by default, and also make `--keepold` on by default.

In particular, users almost always need to use `--keepold` to prevent rendering currently-extant tickets useless (which leads to errors), but it's easy to forget, so it is a footgun.  We should remove the footgun by enabling `--keepold` by default and enabling `prune-key-history` by default as well.

We may need to add new options for kadmin commands to disable `--keepold`.

**Comment by bodik** [comment]
I think that better is to allow exact operations on the keys (ank, cpw, randkey, addenctype, delenctype, newkey keepold, delete kvno), so the Heimdal stays as a good tool as KDC but not a bunch of automagical key management features buried under the hood.

**Comment by nicowilliams** [comment]
See also #480.

**Comment by nicowilliams** [comment]
One issue is that `prune-key-history` is global, but we may need a way to disable that on a per-operation basis.  We could take the `int keepold` argument and make it a three-valued argument with `0` -> `prune all`, `1` -> `prune old`, `2` -> `prune none`.

**Comment by nicowilliams** [comment]
Done with d8394c6.
