### ISSUE TITLE
Add kadmin cpw/randkey option to leave kvno unchanged

### ISSUE THREAD

**Issue by nicowilliams** [heimdal/heimdal#480]
When rotating keys for services shared by multiple hosts it is necessary to first update all the keytabs, *then* change the keys on the KDC:

1. generate new keys;
2. update all the keytabs;
3. set those new keys for the principal in the HDB.

Heimdal's `kadm5` API does support writing new keysets to a principal _without_ changing its kvno, which then makes an alternative cluster key rotation procedure possible:

1. add new keys to the principal in the HDB _without_ changing the principal's current kvno;
2. update all the keytabs;
3. update the principal's kvno in the HDB.

However, we don't have support for this in the kadmin commands.  We need a `--keepkvno` (please suggest better names) option to the `cpw` and `randkey` commands.  The `modify` command already supports setting the kvno of a principal.

**Comment by nicowilliams** [comment]
This one is going to be tough: there's no way in `kadm5_randkey_principal_3()` to not change the kvno.  We'll probably need either new `kadm5` functions and `kadmind` RPCs, or else overload the `keepold` argument -- or overload the `keepold` argument but use new RPCs.  Another option is to have an attribute for "kvno requires explicit change" and then use `kadm5_modify_principal()` to set it.

**Comment by nicowilliams** [comment]
Adding an attribute would be trivial, but for #514.

**Comment by vdukhovni** [comment]
This looks done. Closing the issue.
