### ISSUE TITLE
kdestroy prints incorrect error message and fails on a non-existing cache file

### ISSUE THREAD

**Issue by akesandgren** [heimdal/heimdal#521]
env KRB5CCNAME=FILE:/tmp/nosuchfile kdestroy; echo $?
kdestroy: krb5_cc_destroy: Did not find a plugin for ccache_ops
1

https://github.com/heimdal/heimdal/pull/520 should at least fix _krb5_erase_file to not return errno (ENOENT) in this case.

**Comment by lhoward** [comment]
Can this be closed now that a fix has been committed to master?

**Comment by akesandgren** [comment]
I thought you would handle that.... Closing
