### ISSUE TITLE
Undefined symbol error on Solaris 11 with 7.5

### ISSUE THREAD

**Issue by quanah** [heimdal/heimdal#528]
I noticed this on a Solaris 11 deployment of our product yesterday, and wanted to make note of it.  I'm not sure if this is still an issue or not in the Heimdal 8 work:

`slapd[14345]: [ID 702911 auth.error] unable to dlopen /opt/symas/lib/sasl2/64/libgssapiv2.so.3: ld.so.1: slapd: fatal: relocation error: file /opt/symas/lib/64/libkrb5.so.26: symbol memset_s: referenced symbol not found `

**Comment by lhoward** [comment]
memset_s() should be in libc, right? what version of Heimdal?

**Comment by quanah** [comment]
As noted in the title ;) 7.5

**Comment by quanah** [comment]
And the library is linked to libc:

`
build@sol11-build:/opt/symas/lib/64$ ldd libkrb5.so.26 | grep libc
        libcom_err.so.1 =>       /opt/symas/lib/64/libcom_err.so.1
        libcrypto.so.1.1 =>      /opt/symas/lib/64/libcrypto.so.1.1
        libc.so.1 =>     /lib/64/libc.so.1
        libcryptoutil.so.1 =>    /lib/64/libcryptoutil.so.1
`

And indeed, I see memset_s in libc:

`
build@sol11-build:/opt/symas/lib/64$ strings /lib/64/libc.so.1 | grep memset_s
memset_s.c
memset_s
memset_s
memset_s.c
.memset_setPxQx
memset_s
`

So I don't know why I'm seeing that error.

**Comment by quanah** [comment]
Ok, I figured it out --

I'm building on Solaris 11.4, which has memset_s in libc.

But I deployed on Solaris 11.3, which does *not*. Ugh, I'm going to have to do different builds for different Solaris 11 releases. :(

`
#:/opt/symas/lib/64# strings /lib/64/libc.so.1 | grep memset_s
#:/opt/symas/lib/64#
`

**Comment by jaltman** [comment]
you can build on Solaris 11.3 and deploy to 11.4 but not the reverse

**Comment by lhoward** [comment]
Right, I remember keeping a Solaris 8 SPARC machine around for this reason years ago (recently migrated to hard rubbish).

**Comment by lhoward** [comment]
@quanah what is stopping you building on the lowest version of Solaris you need to support?

**Comment by quanah** [comment]
@lhoward 11.4 adds a bunch of changes that specifically improve performance for our product.

For now, we'll simply build out two different versions (one for 11.3, one for 11.4).

**Comment by lhoward** [comment]
`memset_s()` unfortunately is a tricky one to implement yourself without it being optimised out so, yes, I guess that's probably the best approach.
