### ISSUE TITLE
(at least) Windows run of roken test 'gettadr-infotest' serves no purpse

### ISSUE THREAD

**Issue by rodwiddowson** [heimdal/heimdal#541]
in lib\roken\NTMakefile we see
```test-run:
	cd $(OBJ)
	...stuff...
	-getaddrinfo-test.exe
```
So the test is run with no parameters.   My limited Makefile-fu makes me think that the Linux build is the same.  But the code for this test does nothing unless there are parameters provided. 

Therefore (at least) running this test serves no purpose during a build.

Further, on Windows giving the test parameters fails.  To make it work I needed to add
```
#ifdef _WIN32
    rk_WSAStartup();
#endif
``` 
to `main(argc,argv)`

If someone wants to give me guidance on what sort of parameters would work (`www.h5l.org http` would be as good as any AFAICS) I can make a PR for at least windows.

**Comment by jaltman** [comment]
Instead of conditionally adding rk_WSAStartup() please unconditionally add rk_SOCK_INIT() and rk_SOCK_EXIT().

www.h5l.org would be a fine.

**Comment by rodwiddowson** [comment]
tracked in #544
