### ISSUE TITLE
Windows CRT doesn't support %k as format for strftime

### ISSUE THREAD

**Issue by rodwiddowson** [heimdal/heimdal#542]
The roken test strpftime-test fails because the windows CRT doesn't handle the %k (24 hour clock as a decimal number) format.  See [this link](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/strftime-wcsftime-strftime-l-wcsftime-l?view=vs-2015)

I _suspect_ that the solution is to turn off `HAVE_STRFTIME` in config.h.win32.

**Comment by jaltman** [comment]
Agreed.  Please submit a pull request that does so.

**Comment by rodwiddowson** [comment]
Tracked in #543
