### ISSUE TITLE
Supported Key Distribution Functions

### ISSUE THREAD

**Issue by jeffsani** [heimdal/heimdal#545]
We are attempting to make our virtual platform FIPS 140-2 L1 compliant and came up against this roadblock.  It appears that use of PBKDF2 is not compliant and we must choose one of the 2 options to modify our implementation which we have based on the Heimdal distribution. I will keep this short but just wanted to know if this has come up before with others, and also if either of these other key distribution functions would be supported with Heimdal. 
Basically we can implement SP800-108 to convert the PBKDF2 output to KBKDF output. See SP800-108 - [https://csrc.nist.gov/CSRC/media/Projects/Cryptographic-Algorithm-Validation-Program/documents/KBKDF800-108/kbkdfvs.pdf](https://csrc.nist.gov/CSRC/media/Projects/Cryptographic-Algorithm-Validation-Program/documents/KBKDF800-108/kbkdfvs.pdf)
Or we can modify the distribution to be fully FIPS compliant.  Implement an SP800-38F approved key transport scheme (replacing RC4) – SP800-38F [https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-38F.pdf](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-38F.pdf) 

We based our initial implementation on an older rev of Heimdal - 1.5.3 so I wanted to know if one of the more recent implementations supported **KBKDF** already.

Thanks,
Jeff

**Comment by jaltman** [comment]
[RFC3962](https://www.ietf.org/rfc/rfc3962.txt) and [RFC8009](https://www.ietf.org/rfc/rfc8009.txt) require use of PBKDF2.   Replacing PBKDF2 with KBKDF is an incompatible protocol change. 

To the best of my knowledge there has never been an effort to obtain FIPS certification for Kerberos.  I am also of the believe that using FIPS 140-2 certified implementations would not result in Kerberos being FIPS 140-2 compliant.
