### ISSUE TITLE
heimdal-7.6.0.tar.gz bad signature

### ISSUE THREAD

**Issue by brianmay** [heimdal/heimdal#575]
I seem to be having problems verifying the gpg signature:

```
└> gpg --verify   ../heimdal-7.6.0.tar.gz.asc               
gpg: assuming signed data in '../heimdal-7.6.0.tar.gz'
gpg: Signature made Thu 16 May 2019 08:01:46 AEST
gpg:                using RSA key E65941B71CF3C459A34FA89C45E7572A28CD8CC8
gpg: BAD signature from "Heimdal Release Key <heimdal-discuss@sics.se>" [unknown]
```

**Comment by jaltman** [comment]
Verifies for me with the [signing key](https://www.h5l.org/pgp-signing.txt).

`[D:\downloads] gpg --verify heimdal-7.6.0.tar.gz.asc heimdal-7.6.0.tar.gz
gpg: Signature made 05/15/19 18:01:46 Eastern Daylight Time using RSA key ID 28CD8CC8
gpg: checking the trustdb
gpg: 3 marginal(s) needed, 1 complete(s) needed, PGP trust model
gpg: depth: 0  valid:   2  signed:   5  trust: 0-, 0q, 0n, 0m, 0f, 2u
gpg: depth: 1  valid:   5  signed:   3  trust: 2-, 0q, 0n, 0m, 3f, 0u
gpg: depth: 2  valid:   3  signed:   1  trust: 3-, 0q, 0n, 0m, 0f, 0u
gpg: next trustdb check due at 2019-06-29
gpg: Good signature from "Heimdal Release Key <heimdal-discuss@sics.se>"`

did you add the signing key to your trustdb?

**Comment by brianmay** [comment]
Sorry, it seems like the file was corrupt. Closing...
