### ISSUE TITLE
Trouble locating compile_et when cross-compiling

### ISSUE THREAD

**Issue by chewi** [heimdal/heimdal#60]
I'm trying to cross-build Heimdal. As well as the issues I have already mentioned, I am having trouble with compile_et. I have installed a system copy of Heimdal and provided --with-cross-tools=/usr/sbin/heimdal to configure. This allows asn1_compile to be found but I have a system copy of com_err installed so compile_et is present under /usr/bin rather than /usr/sbin/heimdal. You can normally override the compile_et location with the COMPILE_ET variable but --with-cross-tools takes priority because of this line in configure.ac.

``` bash
ac_cv_prog_COMPILE_ET=${with_cross_tools}compile_et
```

Maybe this would be better?

``` bash
if test "x${COMPILE_ET}" = "x"; then
  COMPILE_ET=${with_cross_tools}compile_et
fi
```

Even then, it still doesn't seem to work because of this line in cf/check-compile-et.m4.

``` bash
if test "${COMPILE_ET}" = "compile_et"; then
```

Even with compile_et in /usr/sbin/heimdal, the test fails because COMPILE_ET is now set to an absolute path. It then goes on to eventually decide that com_err must be missing so it resets COMPILE_ET to `\$(top_builddir)/lib/com_err/compile_et` and bails when it tries to execute the cross-compiled binary. It should probably check that COMPILE_ET is not empty rather than checking for "compile_et" specifically?

Even after resolving all of this, I think it may still force you to use a bundled copy of com_err but I'm having trouble following the logic through so let's deal with the above first.

**Comment by vdukhovni** [comment]
If you find a solution, please open a pull request, which should not have trouble getting merged. Closing this issue for now.
