### ISSUE TITLE
objdir configure fails ("not a git repository")

### ISSUE THREAD

**Issue by kaduk** [heimdal/heimdal#604]
Attempting to build today's master (fcd57af8e1497f4558789251768f9d2900b54679) on debian sid, with an out-of-source objdir (i.e., ```cd .. && mkdir build && cd build && ../heimdal/configure```), configure fails:

```
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands
creating include/version.h
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

**Comment by elric1** [comment]
Can you try elric1/heimdal branch Issue#604?

**Comment by nicowilliams** [comment]
You have to use `--srcdir=...`

**Comment by kaduk** [comment]
@nicowilliams configure still fails even with ```--srcdir=```, for me.
(But Roland's patch fixes it.  I was getting a linker error later in the build when I did not use ```--srcdir=```, but will work on that separately.)

**Comment by jaltman** [comment]
https://github.com/heimdal/heimdal/pull/605 has been merged

**Comment by nicowilliams** [comment]
Strange.  I also built that same commit on Wednesday w/o trouble, and I always do out-of-tree builds.
