### ISSUE TITLE
krb5.conf include support not shipped

### ISSUE THREAD

**Issue by loveshack** [heimdal/heimdal#638]
There has been support in the master branch for the "include" and "includedir" directives in krb5.conf for a couple of years which appears not to have made it into a release.  I assume that's an oversight.
Could you release the support, particularly for compatibility with MIT and assumptions made in GNU/Linux distributions?

**Comment by elric1** [comment]
This support will be in the next release. We have been having discussions amongst ourselves about when we think we should cut the next release, but we have not yet reached consensus. I agree, though, that we should do it relatively soon.
