### ISSUE TITLE
[Question] OSX ccache "API" option

### ISSUE THREAD

**Issue by MisterSpicy** [heimdal/heimdal#644]
I originally sent this to the mailing list, but since it appears to not be working right now, I'm asking here.

Hey all,

I'm trying to familiarize myself with Kerberos, Heimdal, and the ecosystem, and I'm a bit confused by one thing.

In the MIT documentation https://web.mit.edu/kerberos/krb5-1.12/doc/basic/ccache_def.html#ccache-types - it states "API is only implemented on Windows".

Now if I run klist on my osx machine, I get ...

`Credentials cache: API:<UUID>`

Is this a difference in the implementation of kerberos between MIT and Heimdal?  Or is the "API" referenced here something else?

In the end I'd like to be able to read the ccache from a cli I'm writing, but am having trouble understanding the implementation.

**Comment by kaduk** [comment]
The "API:" is unfortunately being used for two different things.
If you consult the current version of the MIT documentation (https://web.mit.edu/kerberos/krb5-latest/doc/basic/ccache_def.html#ccache-types) you will find an additional type "KCM:" -- it is that one which will interoperate with what osx calls "API:".

**Comment by MisterSpicy** [comment]
@kaduk thanks for the reply!  This is a little more clear.  Odd they use 'api'.

**Comment by jaltman** [comment]
In macOS releases up to and including Snow Leopard, the Kerberos implementation was MIT Kerberos.  This changed with macOS Lion in which Apple preserved the public facing APIs but replaced MIT Kerberos with Heimdal Kerberos and a [shim](https://github.com/heimdal/MKShim) that emulates many but not all of the MIT Kerberos API functions.   

The continued use of the "API:" prefix even though the credential cache implementation switched from the MIT Kerberos CCAPI to Heimdal Kerberos KCM was due to the determination that the prefix was part of the public interface that could not be altered.

**Comment by MisterSpicy** [comment]
@jaltman  Do you happen to know how to access the default CCache on OSX?  I know it is in the `Ticket Viewer`, and applications like Chrome and Firefox are able to read it, but I can't seem to figure out how that works.

My uninformed thought is the browsers are using the GSSAPI abstraction to read from the cache and then SPNEGO to authenticate to a secure system - but this may be totally wrong.

**Comment by lhoward** [comment]
Do you mean programatically? You can use `klist` from the command line.

**Comment by MisterSpicy** [comment]
`klist` shows me the principle, the API:<some uuid>, and ticket principle and expiry, but I don't think executing klist as a shell command, say from python or ruby or go, would allow me to utilize a SPNEGO library to make authenticated requests to a secure server?

I'm having a difficult time connecting the dots between the OSX ticket store and using it to make `negotiate` requests.

**Comment by lhoward** [comment]
There are a few layers of abstraction, made all the more complicated by macOS’ slightly unusual history with respect to Kerberos. macOS exposes the GSS-API via GSS.framework, you can use this to establish a security context using SPNEGO (and, thus, Kerberos). GSS.framework is effectively libgssapi from Heimdal, with Apple extensions (which you can find on opensource.apple.com if you're curious, you probably won't be able to build it though).

**Comment by MisterSpicy** [comment]
Cool - I'll take a look at those.  I don't really have an interest in reinventing any wheels here, or compiling any wheels for that matter - only interfacing with it, ideally at a level of abstraction above C.  There are many GSSAPI implementations around for most languages, so my hopes here are to be able to interact with the default keystore through various languages that aren't C or wrapper for C.

**Comment by lhoward** [comment]
I did actually write an Objective-C wrapper called GSSKit which you can find on PADL’s GitHub. Obviously you’d write it in Swift these days. It should still work.

Apple has made some of the GSS types reference counted so you can use them relatively easily from Swift or Objective-C, too.

**Comment by MisterSpicy** [comment]
Neat - any idea if its possible to interface with them in a language like Go or Ruby?  Or are the bindings only for Swift/Obj-C?

**Comment by lhoward** [comment]
I don’t really know enough about either of those languages I’m afraid! I’m curious though so let me know what you find out. If Ruby has an Objective-C bridge you might use GSSKit with it. If C is a better impedance match with your language of choice then, using GSS-APO directly might be a better choice. HTH.
