### ISSUE TITLE
Cant edit NZBget item after edit

### ISSUE THREAD

**Issue by ratnose** [heimdal/heimdal#672]
**Describe the bug**

**To Reproduce**
1. Go to Items config
2. Click on Edit for nzbget

**Expected behavior**
I expected to get to the edit page of the chosen item.

**Desktop (please complete the following information):**
 - OS: Debian 10.1
 - Browser Firefox 71 and 72, Safari 13.0.4
 - Version Latest via hib.docker.com and Linuxserver.io

**Comment by lhoward** [comment]
I think this should have been reported against https://github.com/linuxserver/Heimdall instead of this project. Please reopen if not the case.
