### ISSUE TITLE
kadmin mis-parses commands that include '\' escape characters

### ISSUE THREAD

**Issue by duncan-mcewan** [heimdal/heimdal#704]
I ran into a bug on our NetBSD based KDC host when using "kadmin -l" to change a user's password to include a '"' double quote character and I tried to use a '\' character to escape it.

I believe the bug is present in both the 1.5 release branch and in the 7.7 release.  The relevant file appears not to have been modified in the last nine years.

Earlier this month I reported the bug to the NetBSD project and it has been assigned an ID of 55145
(http://gnats.netbsd.org/cgi-bin/query-pr-single.pl?number=55145).  So far there has been no feedback on that bug report.

The following is a copy of the bug report I submitted to the NetBSD project.  The patches contained in that bug report are also attached.

>Description:  

If you run kadmin (or kadmin -l) in interactive mode and enter command line
parameters containing '\' escape characters, in some circumstances the command
is not parsed correctly.

>How-To-Repeat:  

For eg:

* Try to include the character sequence '\"' in a password

kdc# kadmin -l
kadmin> cpw --password="xxx\\\"yyy" duncan  
sl_loop: out of memory
kadmin> cpw --password=xxx\\"yyy duncan
kadmin>  

I think the 2nd case above only succeeds due to the bug - it  should fail
because of the unescaped '"' character.

* Try to end a password with '"'

kdc# kadmin -l
kadmin> cpw --password="xxx\"" duncan  
sl_loop: out of memory
kadmin> cpw --password=xxx\" duncan  
Arguments given (0) are less than expected (1).

Usage: passwd [-rh] [--random-key] [--random-password] [--password=string]
   [-p string] [--key=string] [--help] principal...
   -r, --random-key             set random key
   --random-password            set random password
   -p string, --password=string princial's password
   --key=string                 DES key in hex

* Try to include spaces in a password using '\' escapes rather than "..."

kdc# kadmin -l
kadmin> cpw --password=xxx\ yyy duncan
kadmin> cpw --password=xxx\\ yyy duncan
kadmin> cpw --password=xxx\\\ yyy duncan  
kadmin: cpw yyy: Principal does not exist
kadmin> cpw --password=xxx\ \ yyy duncan  
kadmin: cpw  yyy: Principal does not exist
kadmin>  

In the above the 1st case seems to work but the password doesn't include the " ".  The 2nd case should result in the error of the 3rd since there's an unescaped ' '.  The 3rd case should work.

>Fix:  
The above failures are all caused by an off-by-one error in lib/sl/sl.c.

I added some extra test cases to test_sl.c.  With the original code these all
fail.  With the patch the original tests and these additional ones all pass.

[sl.c-patch.txt](https://github.com/heimdal/heimdal/files/4542916/sl.c-patch.txt)

[test_sl.c-patch.txt](https://github.com/heimdal/heimdal/files/4542927/test_sl.c-patch.txt)

**Comment by jaltman** [comment]
could you submit the patches as a pull request?

**Comment by duncan-mcewan** [comment]
Sorry - I've never submitted a pull request to a github repository before.  I hope I did it more or less correctly...

**Comment by jaltman** [comment]
Thank you for the fix.  It has been merged.
