### ISSUE TITLE
Symbol not found: _GSS_C_NT_HOSTBASED_SERVICE

### ISSUE THREAD

**Issue by JivanRoquet** [heimdal/heimdal#716]
**Describe the bug**
Trying to use EXASolution ODBC Driver which relies on Kerberos. Using iodbctest on macOS with this driver triggers an error: `Symbol not found: _GSS_C_NT_HOSTBASED_SERVICE (referenced from [..]/libexacli.dylib)`.

**To Reproduce**
- download and install Exasol ODBC driver for macOS [from this page](https://www.exasol.com/portal/display/DOWNLOAD/Version+6.2.3)
- in a terminal, type the following command:
```shell
# no matter the credentials and host/port, as the error is triggered before evaluating them
iodbctest "DRIVER={EXASolution Driver};EXAHOST=*****;EXAPORT=8563;UID=kpler_tableau;PWD=*****;"
```
- the following error output are shown:
```
1: SQLDriverConnect = [iODBC][Driver Manager]dlopen(/Library/ODBC/EXASolution ODBC.bundle/Contents/MacOS/libexaodbc-io418sys.dylib, 6): Symbol not found: _GSS_C_NT_HOSTBASED_SERVICE
  Referenced from: /Library/ODBC/EXASolution ODBC.bundle/Contents/MacOS/libexacli.dylib
  Expec (0) SQLSTATE=00000
2: SQLDriverConnect = [iODBC][Driver Manager]Specified driver could not be loaded (0) SQLSTATE=IM003
```

**Expected behavior**
Expected behaviour is that iodbc opens an SQL session and runs fine.

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.4
 - Version: Heimdal 7.6.0

**Additional context**
Support team at Exasol cannot reproduce the issue, and no matter how many times I've uninstalled and reinstalled their ODBC driver, it will still refuse to work and trigger this `_GSS_C_NT_HOSTBASED_SERVICE` error. This error does not happen with the ODBC driver on Windows or Linux, only on macOS (on this machine).

**Comment by lhoward** [comment]
On Heimdal, the exported symbol for `GSS_C_NT_HOSTBASED_SERVICE` is `__gss_c_nt_hostbased_service_oid_desc` (prefixed by an extra underscore on macOS). This would suggest that the ODBC driver was not built against the version of Heimdal you are trying to link against at runtime.

Note that the `/usr/lib/libgssapi_krb5.dylib` that ships with macOS exports the MIT interface, i.e. it does actually export a `GSS_C_NT_HOSTBASED_SERVICE` symbol (again, `_ GSS_C_NT_HOSTBASED_SERVICE` on macOS) even though the underlying system implementation uses Heimdal. But I don't think this is relevant to your case as it sounds like you are building Heimdal 7.6.0 yourself.

**Comment by lhoward** [comment]
What does `otool -L BC/EXASolution ODBC.bundle/Contents/MacOS/libexaodbc-io418sys.dylib` show?

**Comment by JivanRoquet** [comment]
Thanks @lhoward , the output of this `otool` command is:

```
/Library/ODBC/EXASolution ODBC.bundle/Contents/MacOS/libexaodbc-io418sys.dylib:
	libexaodbc-io418sys.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libiodbcinst.2.dylib (compatibility version 4.0.0, current version 4.18.0)
	@loader_path/libexacli.dylib (compatibility version 0.0.0, current version 0.0.0)
	@loader_path/libgmp.10.dylib (compatibility version 14.0.0, current version 14.2.0)
	@loader_path/libUnicodeMapping.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.250.1)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.4)
```

Since you're saying that the ODBC driver was not built against the version I'm trying to link against, is there a way to know which Heimdal version I should be linking?

**Comment by lhoward** [comment]
Hmm. Is there a configuration directive in the driver to specify the GSS library? Looks like it must be loaded at runtime. And looks like it might be expecting a MIT compatible ABI.

**Comment by JivanRoquet** [comment]
Alright, thanks for these precisions. Is it possible to get a version of Heimdal/Kerberos which is still MIT compatible?

**Comment by lhoward** [comment]
The version that ships with macOS is the easiest way to do it. Point it to /use/lib/libgssapi_krb5.dylib. Or use MIT :)

**Comment by lhoward** [comment]
Closing this, as it is not an issue with Heimdal itself.

**Comment by JivanRoquet** [comment]
Cool, thanks for the input @lhoward
