### ISSUE TITLE
README file has outdated contact info

### ISSUE THREAD

**Issue by knuta** [heimdal/heimdal#734]
It appears that the [README](https://github.com/heimdal/heimdal/blob/master/README) file is outdated. The links point to domains which redirect to GitHub and gives 404s, and the mailing lists appear defunct. I was at least unable to subscribe to heimdal-discuss-request@sics.se with the following message in the bounce:

```
550 5.4.1 Recipient address rejected: Access denied. AS(201806281) [AM5EUR02FT021.eop-EUR02.prod.protection.outlook.com]
```

Is there a replacement for the list, or an IRC channel perhaps? Any pointers for where to get help debugging issues would be greatly appreciated.

**Comment by lhoward** [comment]
README.md is up to date, so perhaps we can just remove README – @nicowilliams?

**Comment by knuta** [comment]
@lhoward, README.md is actually also outdated -- the link to installation instructions is dead (readirects to a GitHub 404):

> For information how to install see [here](http://www.h5l.org/compile.html).

**Comment by lhoward** [comment]
I don't have a good answer for this right now (beyond removing the link) because the documentation needs to be built from sources. (And, ideally automatically, so it stays up to date.)

**Comment by jaltman** [comment]
README and README.md have been updated on master.

**Comment by jaltman** [comment]
To subscribe to the current mailing lists send mail to heimdal-announce-subscribe@heimdal.software or heimdal-discuss-subscribe@heimdal.software
