### ISSUE TITLE
Button tool-tips

### ISSUE THREAD

**Issue by deef0000dragon1** [heimdal/heimdal#749]
**Is your feature request related to a problem? Please describe.**
It is very difficult to determine what the different icons in the bottom corner are for new users. Even with using it for a bit, I still get confused as to what does what, and basically have to go down the line to find what I am looking for.

**Describe the solution you'd like**
Please add tool-tips to the buttons, or 
Pop out the button title (Users, Items, Tags etc) when hovered over, and add a description tool-tip (This is where the different items that are linked to can be edited, This is where you add and remove users, This is the item dashboard, showing pinned links)

**Describe alternatives you've considered**
Memorizing what the icons do would be an ideal end goal for a user, but adding tool-tips will improve new user experience

**Comment by lhoward** [comment]
Is this related to Heimdal, the Kerberos implementation?

**Comment by deef0000dragon1** [comment]
I indeed commented on the wrong heimdal. My apologies.
