### ISSUE TITLE
heimdal-devel on CentOS 8 not pkgconfig aware

### ISSUE THREAD

**Issue by Akrugerus** [heimdal/heimdal#765]
When installing heimdal-dev on Debian with apt, the installation creates heimdal-*.pc files so that pkgconfig is aware of heimdal. When installing heimdal-devel on CentOS 8 with dnf, the installation does not create the relevant pkgconfig files and requires unnecessary extra work for pkconfig to find heimdal.

**Comment by quanah** [comment]
Sounds like an issue you should take up with the RedHat packaging team?

**Comment by frozencemetery** [comment]
Well, the CentOS team, but otherwise yes.  (We don't ship Heimdal in RHEL - I maintain mit-krb5 there.)

**Comment by quanah** [comment]
@frozencemetery thanks for the confirmation, closing this issue.

**Comment by 00willo** [comment]
Just adding some extra information for those arriving here via google. 

`heimdal-devel` is provided by epel-8. There's also already a bugzilla ticket for it. 

https://bugzilla.redhat.com/show_bug.cgi?id=1931072

**Comment by 00willo** [comment]
This also affects CentOS 7.
