### ISSUE TITLE
libasn1 causes Apache to crash when trying to use Crypt::PK::ECC

### ISSUE THREAD

**Issue by ailin-nemui** [heimdal/heimdal#770]
**Describe the bug**
The Crypt::PK::ECC [1] module can be used for Java Web Tokens amongst other things. It uses the tomcrypt library [2] do to this. That library has a function called 

    int der_length_octet_string(unsigned long noctets, unsigned long *outlen);

Unfortunately, when loaded into Apache, the system uses the 

    size_t der_length_octet_string (const heim_octet_string *k)

function from libasn1.

- OS: Ubuntu 18.04

Stack trace looks like this:
```
Program received signal SIGSEGV, Segmentation fault.
0x00007fa7a8922a80 in der_length_octet_string () from target:/usr/lib/x86_64-linux-gnu/libasn1.so.8
(gdb) bt
#0  0x00007fa7a8922a80 in der_length_octet_string () from target:/usr/lib/x86_64-linux-gnu/libasn1.so.8
#1  0x00007fa78b535ce4 in der_decode_custom_type_ex (
    in=in@entry=0x55e4c009b1b0, 
    inlen=inlen@entry=86, root=root@entry=0x0, list=list@entry=0x7ffc49fcdf40, outlen=outlen@entry=4, flags=flags@entry=1)
    at ltc/pk/asn1/der/custom_type/der_decode_custom_type.c:223
...
```

I suppose this is a general issue with any C code, but do you have any suggestions by chance?

[1] https://github.com/DCIT/perl-CryptX/issues/68
[2] https://github.com/libtom/libtomcrypt/blob/develop/src/headers/tomcrypt_pk.h

**Comment by nicowilliams** [comment]
Are you linking statically?  My suggestion would be: don't link statically.

**Comment by nicowilliams** [comment]
Another possibility would be to have us extract our ASN.1 compiler and library and get Tom to use it and commonalize more between the two codebases.

**Comment by ailin-nemui** [comment]
thanks for your response, to be honest I'm not entirely on top of C, symbols, and linking.

For instance, why does Apache load libasn1? I suspect it is because of mod_auth_gssapi or something similar.

Secondly, the libasn1 has these methods in the library, but they don't seem to be exposed in any header file. In that case, should these symbols maybe be hidden? Is this possible in C to hide these symbols?

Thirdly, the problem I am facing is with Perl modules (another layer of indirection if you so wish). The CryptX module will be another shared object, but it consumes (to the best I can tell) the tomcrypt library in a static fashion, but the end result will be a shared module. As a result, the Perl module CryptX.so will also (again, as far as I understand) have the der_length_octet_string symbol (amongst all the other tomcrypt symbols). However, Apache/libperl/mod_perl will still resolve the function from the first library they have loaded. So maybe another question is if CryptX could somehow ensure that it loads its own functions.

Thanks

**Comment by ailin-nemui** [comment]
How would not linking statically help here?

**Comment by abartlet** [comment]
Dynamic linking allows the use of symbol versions which is one
important way past this issue.

This allow Samba (for example) to cope while linked to both an internal
copy of Heimdal and the system MIT Kerberos (via dependencies) and not
suffer horribly, or BIND9 to link to MIT Kerberos and load a plugin
from Samba (our DLZ module).

**Comment by ailin-nemui** [comment]
do you have any idea/details how to apply this to perl-CryptX / apache lib_ldap? The CryptX author doesn't know https://github.com/DCIT/perl-CryptX/issues/68

**Comment by atoomic** [comment]
This was a problem from perl-CryptX advertising the symbols when it should not.
The patch from https://github.com/DCIT/perl-CryptX/pull/79 should now fix this issue
