### ISSUE TITLE
Info how to build/compile incomplete/wrong

### ISSUE THREAD

**Issue by habazut** [heimdal/heimdal#773]
**Describe the bug**

On this page https://github.com/heimdal/heimdal/tree/heimdal-7.7.0 it says:
For information how to install see <http://www.h5l.org/compile.html>.
But that only points to https://github.com/heimdal/ which is not a page with install info.

On this page https://github.com/heimdal/heimdal it says:
For information how to install see here (https://github.com/heimdal/heimdal/wiki/Building-and-installing)
There it says: ./configure
But the downloaded zip from github does not contain ./configure

**To Reproduce**

Try to follow the instructions as a person that has not already everyting setup.

**Expected behavior**

Clean and easy instructions how to build

1. Dowload (tar or zip) file
2. Run these commands

** Version **

I tried to get 7.7.0

Regards,
Harald.

**Comment by iinuwa** [comment]
> Heimdal uses GNU Autoconf to configure for specific hosts, and GNU Automake to manage makefiles. If this is new to you the short instruction is to run the configure script in the top level directory and when that finishes make.

The part where it says "to run the configure script," I believe this refers to the `autogen.sh` script in the root of the directory. If you run that, the `configure` script will be generated.

**Comment by abartlet** [comment]
The documentation is targeted at folks using a release tarball, where
this would be included.

But build-from-git is becoming more common, and an extra note would not
go astray.
