### ISSUE TITLE
mech/gss_display_status.c:95: possible missing comma ?

### ISSUE THREAD

**Issue by dcb314** [heimdal/heimdal#775]
mech/gss_display_status.c:95:2: warning: suspicious concatenation of string literals in an array initialization; did you mean to separate the elements with a comma? [-Wstring-concatenation]

Source code is

       "A token had an invalid MIC",
        "No credentials were supplied, "
        "or the credentials were unavailable or inaccessible.",

Maybe better code

       "A token had an invalid MIC",
        "No credentials were supplied, ",
        "or the credentials were unavailable or inaccessible.",

**Comment by lhoward** [comment]
The string concatenation is intended, it is there for readability to avoid a long line.

**Comment by lhoward** [comment]
We should find a way to suppress the warning, though.
