### ISSUE TITLE
Dependency issue with vis.h

### ISSUE THREAD

**Issue by abartlet** [heimdal/heimdal#777]
Ubuntu 20.04 does not have vis.h - it has bsd/vis.h, but vis.h is not found by configure.  Which should be fine, Heimdal provides a replacement. 

However I get the below:

```
make[3]: Entering directory '/home/abartlet/heimdal/lib/roken'
  CC       rkvis-vis.o
vis.c:79:10: fatal error: vis.h: No such file or directory
   79 | #include <vis.h>
      |          ^~~~~~~
compilation terminated.
make[3]: *** [Makefile:2090: rkvis-vis.o] Error 1
make[3]: Leaving directory '/home/abartlet/heimdal/lib/roken'
make[2]: *** [Makefile:1147: all] Error 2
make[2]: Leaving directory '/home/abartlet/heimdal/lib/roken'
make[1]: *** [Makefile:577: all-recursive] Error 1
make[1]: Leaving directory '/home/abartlet/heimdal/lib'
make: *** [Makefile:624: all-recursive] Error 1
```

It looks like a depenency issue to me in the Makefile.am chain, but I'm a bit lost in there, as if I ran:
```
$ cd lib/roken/
abartlet@abartlet-lp:~/heimdal/lib/roken$ make vis.h
cp vis.hin vis.h
```
And try building again, it works (up to the next issue)

**Comment by lhoward** [comment]
OK, maybe Makefile.am needs

`$(vis_h): vis.hin`

Can you use variables on the LHS?

**Comment by lhoward** [comment]
Ah, it's a typo! Should be $(vis_h) in BUILT_SOURCES.

**Comment by lhoward** [comment]
Please try ab8d4f508e0a9488f8292443135096af78028c7a or master

**Comment by jborean93** [comment]
Looks like that's done the trick, thanks!

**Comment by iboukris** [comment]
Works for me too, thanks all!

**Comment by lhoward** [comment]
Sorry for taking so long! I get to them as time permits...
