### ISSUE TITLE
test_nist seems to spin

### ISSUE THREAD

**Issue by abartlet** [heimdal/heimdal#781]
**Describe the bug**
make check spins running 'test_nist'

**To Reproduce**
Steps to reproduce the behaviour:
1. ./autogen.sh
2. ./configure
3. make -j8
4. make check

**Expected behavior**
Tests run to conclusion

**Observed behaviour**

test_nist seems to spin forever

**OS/Distro**

I'm running Ubuntu 20.04

**Comment by abartlet** [comment]
I've traced this and it does seem to be making forward progress sometimes, and othertimes seems to take almost forever. 

This discourages running 'make check' on proposed MRs.  Clues as to what is going on would be most welcome.

**Comment by nicowilliams** [comment]
Can you run `cd lib/hx509 && bash -vx test_nist`?  What's it doing?

**Comment by abartlet** [comment]
I think I've worked it out.  Local issue most likely.
