### ISSUE TITLE
[BUG]several potential bugs of  NULL Pointer Dereference

### ISSUE THREAD

**Issue by Hyxl1017** [heimdal/heimdal#817]
hello,I found some bugs of null pointer dereference/unchecked return value to null pointer dereference in source code of heimdal,would you help me check whether these bugs are true?thank you very much for your patience and effort.

there are several potential bugs of  NULL Pointer Dereference :
==============================================================================

step  1 : 
	 In file  heimdal/lib/roken/resolve.c , function  rk_dns_type_to_string   line  95 :
 		 Select the false branch at this point (p.0->name!=null is false) 

step  2 : 
	 In file  heimdal/lib/roken/resolve.c , function  rk_dns_type_to_string   line  99 :
 		 Return null to caller 

step  3 : 
	 In file  heimdal/lib/roken/resolve.c , function  dns_lookup_int   line  557 :
 		 Function rk_dns_type_to_string executes and returns 

step  4 : 
	 In file  heimdal/lib/roken/resolve.c , function  dns_lookup_int   line  556 :
                 The return value of function rk_dns_type_to_string is passed to function fprintf as a variadic argument (the return value of function rk_dns_type_to_string can be null) 

==============================================================================

step  1 : 
	 In file  heimdal/lib/roken/resolve.c , function  rk_dns_type_to_string   line  95 :
 		 Select the false branch at this point (p.0->name!=null is false) 

step  2 : 
	 In file  heimdal/lib/roken/resolve.c , function  rk_dns_type_to_string   line  99 :
 		 Return null to caller 

step  3 : 
	 In file  heimdal/lib/roken/resolve.c , function  dns_lookup_int   line  569 :
 		 Function rk_dns_type_to_string executes and returns 

step  4 : 
	 In file  heimdal/lib/roken/resolve.c , function  dns_lookup_int   line  568 :
 		 The return value of function rk_dns_type_to_string is passed to function fprintf as a variadic argument (the return value of function rk_dns_type_to_string can be null) 

==============================================================================

step  1 : 
	 In file  heimdal/lib/asn1/gen.c , function  generate_constant   line  529:
 		 Allocate memory to gen_upper (lacking failure check, 81 out of 130 memory allocations checked failures) 

step  2 : 
	 In file  heimdal/lib/asn1/gen.c , function  generate_constant   line  530:
 		 gen_upper used as the 1st parameter of strlen(gen_upper can be null)

==============================================================================

step  1 : 
	 In file  heimdal/lib/asn1/gen_template.c , function  tlist_new   line  292:
 		 Store the allocated memory to tl->name (lacking failure check, 81 out of 130 memory allocations checked failures) 

step  2 : 
	 In file  heimdal/lib/asn1/gen_template.c , function  tlist_new   line  294:
 		 Program reaches the return point, modifying the value tl->name to null, where tl is the return value 

step  3 : 
	 In file  heimdal/lib/asn1/gen_template.c , function  generate_template_type   line  1403:
 		 Function tlist_new modifies the value tl->name to null, where tl gets the return value 

step  4 : 
	 In file  heimdal/lib/asn1/gen_template.c , function  generate_template_type   line  1439:
 		 tl->name is passed to function fprintf as a variadic argument (tl->name can be null) 

==============================================================================

step  1 : 
	 In file  heimdal/lib/asn1/gen_template.c , function  add_line   line  422 :
 		 Allocate memory to q (lacking failure check, 81 out of 130 memory allocations checked failures) 

step  2 : 
	 In file  heimdal/lib/asn1/gen_template.c , function  add_line   line  425 :
 		 Load value from q->line 

==============================================================================

step  1 : 
	 In file  heimdal/lib/roken/roken_gethostby.c , function  split_spec   line  91 :
 		 Store the allocated memory to host (lacking failure check, 81 out of 130 memory allocations checked failures) 

step  2 : 
	 In file  heimdal/lib/roken/roken_gethostby.c , function  split_spec   line  92 :
 		 host is used as the 1st parameter in function strchr (host can be null) 

==============================================================================

step  1 : 
	 In file  heimdal/lib/asn1/gen_template.c , function  tlist_new   line  291 :
 		 Allocate memory to tl (lacking failure check, 81 out of 130 memory allocations checked failures) 

step  2 : 
	 In file  heimdal/lib/asn1/gen_template.c , function  tlist_new   line  292 :
 		 Store the allocated memory to tl->name 

==============================================================================

step  1 : 
	 In file  heimdal/lib/libedit/src/chartype.c , function  ct_decode_string   line  139 :
 		 Return null to caller 

step  2 : 
	 In file  heimdal/lib/libedit/src/prompt.c , function  prompt_print   line  97 :
 		 Function ct_decode_string executes and stores the return value to p (p can be null) 

step  3 : 
	 In file  heimdal/lib/libedit/src/prompt.c , function  prompt_print   line  100 :
 		 Load value from *(p) 

 		
there are several potential bugs of  Unchecked Return Value to NULL Pointer Dereference :
==============================================================================

step  1 : 
	 In file  heimdal-7.5.0+dfsg/lib/libedit/src/filecomplete.c , function  fn_complete   line  444 :
 		 Allocate memory to temp (lacking failure check, 112 out of 164 memory allocations checked failures) 

step  2 : 
	 In file  heimdal-7.5.0+dfsg/lib/libedit/src/filecomplete.c , function  fn_complete   line  446 :
 		 Store 0 to temp[len] 

==============================================================================

step  1 : 
	 In file  heimdal-7.5.0+dfsg/lib/sl/sl.c , function  osad   line  408/409/410 :
 		 Allocate memory to row0/row1/row2 (lacking failure check, 112 out of 164 memory allocations checked failures) 

step  2 : 
	 In file  heimdal-7.5.0+dfsg/lib/sl/sl.c , function  osad  , lines  after allocation:
 		 there are many statement derefer row0/row1/row2 without check if allocation is successful.

==============================================================================

step  1 : 
	 In file  heimdal-7.5.0+dfsg/lib/libedit/src/chartype.c , function  ct_decode_argv   line  159 :
 		 Allocate memory to wargv (lacking failure check, 112 out of 164 memory allocations checked failures) 

step  2 : 
	 In file  heimdal-7.5.0+dfsg/lib/libedit/src/chartype.c , function  ct_decode_argv   line  163/166 :
 		 Store null/p to wargv[i]

**Comment by abartlet** [comment]
Thanks for your interest in to improving Heimdal.

Can you please, when reporting these issues, list the tool used, the parameters given etc.  

Also, a separate issue per problem will allow these to be worked down one at a time.

However, even better are tested patches that fix the issue.

For an example of the kind of detail I've found helpful in getting similar things fixed in the past, look at these pull requiests: #811 #791 #784 #722

In terms of issues without a fix, these move slower so #793 and #792 are good examples of why including a patch is better.

**Comment by Hyxl1017** [comment]
Thanks for your reply.
These problems are obtained by analyzer we are developing staticly.
I will report each problem in separate issue.
Thanks.
