### ISSUE TITLE
[BUG]a bug of  Memory Leak

### ISSUE THREAD

**Issue by Hyxl1017** [heimdal/heimdal#818]
hello,I found a bug of memory leak in source code of heimdal,would you help me check whether this bug is true?thank you very much for your patience and effort.

there is a potential bug of  Memory Leak :

==============================================================================

step  1 : 
	 In file  heimdal-7.5.0+dfsg/include/bits.c , function  main   line  133 :
 		 Allocate memory to p 
step  2 : 
	 In file  heimdal-7.5.0+dfsg/include/bits.c , function  main   line  133:
 		 there is no free statement to free p after allocation

**Comment by lhoward** [comment]
It is a leak – feel free to submit a PR, but it's not really an issue because `bits` is only used to compile Heimdal, and the memory will be freed as soon as `main()` exits (which is shortly after `malloc()` is called).
