### ISSUE TITLE
krb5_enomem not declared with Windows calling convention

### ISSUE THREAD

**Issue by lhoward** [heimdal/heimdal#834]
`krb5_enomem()` is not declared `KRB5_LIB_CALL` which breaks if the application’s default calling convention is not cdecl.

We cannot change this without breaking ABI compatibility (although there are apparently some hacks which allow a function to support both calling conventions).

**Comment by jaltman** [comment]
I am fine with fixing the calling convention of krb5_enomem() on windows.   it was implemented for use as an internal function within the library but more importantly, on Windows, the DLLs are built and distributed as a signed assembly.   As a result it shouldn't be possible to mix new and old DLLs.

**Comment by jaltman** [comment]
I would also be fine if krb5_enomem was converted to a static inline function.
