### ISSUE TITLE
No CI running on pull requests

### ISSUE THREAD

**Issue by abartlet** [heimdal/heimdal#876]
**Describe the bug**
There is no CI on new pull requests, which means ideas are proposed that may not, in the current form against current master, pass `make check`

**To Reproduce**
1. Make a Heimdal change
2. Submit a github pull request
3. Possibly break master or be asked why it fails make check

**Expected behavior**
A clear CI failure

I'm just wondering what the current blockers and feelings are regarding CI in case we can help.  Samba is doing very well on GitLab with GitLab CI currently, which is trying to provide a decent amount of free CI for open source (currently unlimited, but soon to be reduced).  Samba also uses our own runners in a paid RackSpace cloud to augment the free service.

On the flip side, Red Hat has mentioned their offers of CI for GitHub for open source projects via a Jenkins.

**Comment by abartlet** [comment]
I realise things were OK until Travis CI went away and then it seems the windows testing has broken as well.  I know well the pain of how much time it takes to set this stuff up or get it working again, that is not in question, I just want to know the feeling and direction before I stumble into the area.

**Comment by lhoward** [comment]
Windows testing is working again.

**Comment by nicowilliams** [comment]
Appveyor is working now.  GitHub actions should be too, except they just stopped running on my PR (#927) and I don't know why.  I suspect I've hit some quota?  But it's not telling me.

**Comment by iboukris** [comment]
Often happens due to yml syntax, try take a look at: https://github.com/heimdal/heimdal/actions

**Comment by nicowilliams** [comment]
> Often happens due to yml syntax, try take a look at: https://github.com/heimdal/heimdal/actions

That's exactly what it was.

Anyways, we now have GitHub actions for Linux and Windows, and we have Appveyor.  Next up: OS X.
