### ISSUE TITLE
Conflicting der_* function: consider isolating them with a prefix 

### ISSUE THREAD

**Issue by atoomic** [heimdal/heimdal#911]
**Describe the bug**

All the `der_*` functions in `lib/asn1/der*` directory are then advertised in the .so file and can conflict with other libraries.
We should consider isolating them by adding a prefix like `hx509_` 

**To Reproduce**

In my case I was compiling a binary which was using these two libraries:
- /lib/x86_64-linux-gnu/libhx509.so.5
- 532/lib/perl5/cpanel_lib/x86_64-linux-64int/auto/CryptX/CryptX.so

`libhx509.so.5` and `CryptX/CryptX.so` are both advertising some `der_*` functions which are  not compatible...

`der_length_integer` is available from both libraries
but only `der_decode_integer` is availabe from CryptX.so 

**Expected behavior**
Isolate vendor functions

**Comment by lhoward** [comment]
They should probably have a `heim_` prefix. Just need to do it when there's an ABI version bump.

**Comment by sjaeckel** [comment]
As this has a sibling issue in ltc as well, here my 2c on it https://github.com/libtom/libtomcrypt/issues/582#issuecomment-1003404763

**Comment by atoomic** [comment]
Thanks @sjaeckel for your feedback, I think we can close this case as we were able to find the correct way to do not advertise these functions and thus avoid the conflict.
There is nothing wrong here IMO.

**Comment by sjaeckel** [comment]
Well I'm not sure if there's nothing wring here as heimdal exposing ltc API's is still prone to the same error with other applications.
IMO heimdal should also hide the ltc symbols.
