### ISSUE TITLE
heimdal-kdc leaks memory

### ISSUE THREAD

**Issue by brianmay** [heimdal/heimdal#93]
Hello,

This was reported at http://bugs.debian.org/746486.

> We use heimdal kdc to authenticate more than 30k users in multiple services. After upgrading from squeeze to wheezy the KDC process started to leak memory (~2GiB/week). We don't use the binary package of wheezy, but source package is rebuilt with a little patch  enabling impersonation of other pricipals. It is belived that this should not cause the problem.
> 
> We had it run under valgrind for some hours, the output is attached.
> Our patch in importable with quilt import also attached.

There is a Valgrind log attached, see:
https://bugs.debian.org/cgi-bin/bugreport.cgi?msg=5;filename=valgrind_0417;att=1;bug=746486

Thanks

**Comment by vdukhovni** [comment]
It looks like this particular issue was fixed.  Closing.  Please reopen if I missed something
