### ISSUE TITLE
KRB5 GSS mechanism doesn't seem to enforce ticket expiration

### ISSUE THREAD

**Issue by sthaber** [heimdal/heimdal#931]
Hi there! We're writing an NFSv4.1 server that uses Heimdal for its Kerberos capabilities. We discovered that Heimdal does not enforce ticket expiration for the KRB5 GSS mechanism (OID 1.2.840.113554.1.2.2). By this I mean that the following methods succeed when an expired Kerberos ticket (system_time > ticket.endtime) is provided to Heimdal:
- gss_accept_sec_context
- gss_get_mic
- gss_verify_mic
- gss_wrap
- gss_unwrap
- Perhaps other methods that we haven't tried yet

Heimdal is clearly aware that the ticket is expired. If we call gss_context_time, we get a GSS_S_CREDENTIALS_EXPIRED major status. Yet the above methods continue to succeed. This behavior is surprising. According to the GSS C bindings specification (RFC2744), GSS_S_CREDENTIALS_EXPIRED can (should?) be returned from all of the above mentioned methods. We have also observed that other mechanisms do seem to enforce this behavior. For example, our usage of SPNEGO (OID 1.3.6.1.5.5.2) seems to correctly fail Kerberos handshakes with an expired ticket by falling back to other SPNEGO mechanisms in a MORE_PROCESSING_REQUIRED loop. 

However this seems too deliberate to just be a bug. We're wondering if anyone knows what the reasoning behind not checking expiration anywhere is?

**Comment by lhoward** [comment]
https://krbdev.mit.narkive.com/ztY5Mm31/gssapi-context-lifetime

**Comment by lhoward** [comment]
I asked the rest of the team: the decision from the Kitten WG was that context expiration should be enforced by the application, not the library, so it can decide its own policy and/or enforce clean termination. So you can check with `gss_context_time()` and implement your own policy if desired. Closing.

**Comment by lhoward** [comment]
`gss_accept_sec_context()` shouldn't accept expired tickets. If it does, please reopen; it's a serious bug. However see this code in `krb5_decrypt_ticket()`:

```c
KRB5_LIB_FUNCTION krb5_error_code KRB5_LIB_CALL
krb5_decrypt_ticket(krb5_context context,
                    Ticket *ticket,
                    krb5_keyblock *key,
                    EncTicketPart *out,
                    krb5_flags flags)
{
    EncTicketPart t;
    krb5_error_code ret;
    ret = decrypt_tkt_enc_part (context, key, &ticket->enc_part, &t);
    if (ret)
        return ret;

    {
        krb5_timestamp now;
        time_t start = t.authtime;

        krb5_timeofday (context, &now);
        if(t.starttime)
            start = *t.starttime;
        if(start - now > context->max_skew
           || (t.flags.invalid
               && !(flags & KRB5_VERIFY_AP_REQ_IGNORE_INVALID))) {
            free_EncTicketPart(&t);
            krb5_clear_error_message (context);
            return KRB5KRB_AP_ERR_TKT_NYV;
        }
        if(now - t.endtime > context->max_skew) {
            free_EncTicketPart(&t);
            krb5_clear_error_message (context);
            return KRB5KRB_AP_ERR_TKT_EXPIRED;
        }

        if(!t.flags.transited_policy_checked) {
            ret = check_transited(context, ticket, &t);
            if(ret) {
                free_EncTicketPart(&t);
                return ret;
            }
        }
    }

    if(out)
        *out = t;
    else
        free_EncTicketPart(&t);
    return 0;
}
```

i.e. `KRB5KRB_AP_ERR_TKT_EXPIRED` will be returned.

**Comment by sthaber** [comment]
Thanks for getting back to me so quickly. We have a test that we're developing against right now where `gss_accept_sec_context` is accepting an out of date ticket. We're forcing this behavior by using a KDC with 60 expiration and waiting 70 seconds before handing the ticket blob to the accept. We are currently working around this behavior by having our application check the time itself, as you suggested. If we do this check immediately after the accept, then we can catch the error. I'm thinking now that maybe our test is too synthetic because of the `max_skew` in the code snippet above. We'll debug further and reopen if it looks like Heimdal is accepting the ticket even when the endtime + skew has been exceeded. Thanks!

**Comment by sthaber** [comment]
Yup, no bug here. Sorry for the noise.
