### ISSUE TITLE
Support for multiple CRLs in `pkinit_revoke` parameter

### ISSUE THREAD

**Issue by wokis** [heimdal/heimdal#991]
**Is your feature request related to a problem? Please describe.**
`pkinit_anchors` supports `DIR:`, however `pkinit_revoke` does not.

**Describe the solution you'd like**
Add `DIR:` support for `pkinit_revoke`.

**Describe alternatives you've considered**
Comma separation of files, such as used in `pkinit_identity` does not work either.

**Additional context**
n/a

**Comment by nicowilliams** [comment]
Good idea.

**Comment by nicowilliams** [comment]
I'm having a difficult time nailing down the exact `Name` hashing algorithm in OpenSSL...

**Comment by nicowilliams** [comment]
See #1066.

**Comment by nicowilliams** [comment]
> Comma separation of files, such as used in pkinit_identity does not work either.

Making _that_ work is the simplest thing right now, and you're right, this is a pretty necessary feature!

**Comment by nicowilliams** [comment]
Since what you're asking for is a way to have multiple PKINIT issuers and CRLs I'll change the title, and since that feature exists, I'll close this.

**Comment by wokis** [comment]
@nicowilliams Sorry for the one year late response. While `pkinit_revoke` is multi-valued it still differs in they way that `pkinit_anchors` supports `DIR:` while `pkinit_revoke` does not. Any chance we can revisit PR #993?

MIT krb5 claims to support `DIR:` for `pkinit_revoke`. It would be nice if Heimdal did the same.
